export const enum EStripeErrorCodes {
  /**
   * Stripe Payments service operations
   */
  DOWNLOAD_RECEIPT_FAILED = "STRIPE.PAYMENTS.DOWNLOAD_RECEIPT_FAILED",
  FETCH_RECEIPT_DATA_FAILED = "STRIPE.PAYMENTS.FETCH_RECEIPT_DATA_FAILED",
  RECEIPT_DOWNLOAD_REQUEST_FAILED = "STRIPE.PAYMENTS.RECEIPT_DOWNLOAD_REQUEST_FAILED",
  /**
   * Stripe Connect service operations
   */
  INSTANT_BALANCE_MISSING = "STRIPE.CONNECT.INSTANT_BALANCE_MISSING",
}
