export const enum EAppointmentOrderSharedErrorCodes {
  /**
   ** Shared logic operations
   */
  ORDER_MISSING_IN_APPOINTMENT = "APPOINTMENT_ORDER_SHARED.SHARED_LOGIC.ORDER_MISSING_IN_APPOINTMENT",
  GROUP_MISSING_IDS = "APPOINTMENT_ORDER_SHARED.SHARED_LOGIC.GROUP_MISSING_IDS",
  ORDER_GROUP_NOT_FOUND = "APPOINTMENT_ORDER_SHARED.SHARED_LOGIC.ORDER_GROUP_NOT_FOUND",
  ORDER_NOT_FOUND = "APPOINTMENT_ORDER_SHARED.SHARED_LOGIC.ORDER_NOT_FOUND",
  INTERPRETER_PROFILE_NOT_FOUND = "APPOINTMENT_ORDER_SHARED.SHARED_LOGIC.INTERPRETER_PROFILE_NOT_FOUND",
  INTERPRETER_TEMPORARILY_BLOCKED = "APPOINTMENT_ORDER_SHARED.SHARED_LOGIC.INTERPRETER_TEMPORARILY_BLOCKED",
  /**
   ** Search time frame operations
   */
  UNABLE_TO_DETERMINE_TIME_CATEGORY = "APPOINTMENT_ORDER_SHARED.SEARCH_TIME_FRAME.UNABLE_TO_DETERMINE_TIME_CATEGORY",
  UNSUPPORTED_TIME_CATEGORY = "APPOINTMENT_ORDER_SHARED.SEARCH_TIME_FRAME.UNSUPPORTED_TIME_CATEGORY",
}
