export const enum EDocusignErrorCodes {
  /**
   * Common operations
   */
  COMMON_CONTRACT_NOT_AVAILABLE_FOR_ROLE = "DOCUSIGN.COMMON.CONTRACT_NOT_AVAILABLE_FOR_ROLE",
  COMMON_ALREADY_SIGNED = "DOCUSIGN.COMMON.ALREADY_SIGNED",
  COMMON_CONTRACT_ALREADY_COMPLETED = "DOCUSIGN.COMMON.ALREADY_COMPLETED",
  COMMON_NO_DOCUMENTS = "DOCUSIGN.COMMON.NO_DOCUMENTS",
  /**
   * Individual contract operations
   */
  INDIVIDUAL_INVALID_USER_STATUS = "DOCUSIGN.INDIVIDUAL.INVALID_USER_STATUS",
  INDIVIDUAL_COUNTRY_NOT_DEFINED = "DOCUSIGN.INDIVIDUAL.COUNTRY_NOT_DEFINED",
  INDIVIDUAL_STEPS_NOT_COMPLETED = "DOCUSIGN.INDIVIDUAL.STEPS_NOT_COMPLETED",
  INDIVIDUAL_CONTACT_EMAIL_NOT_SPECIFIED = "DOCUSIGN.INDIVIDUAL.CONTACT_EMAIL_NOT_SPECIFIED",
  INDIVIDUAL_PROFILE_NOT_DEFINED = "DOCUSIGN.INDIVIDUAL.PROFILE_NOT_DEFINED",
  INDIVIDUAL_CONTRACT_NOT_COMPLETED = "DOCUSIGN.INDIVIDUAL.CONTRACT_NOT_COMPLETED",
  INDIVIDUAL_CONTRACT_FILE_ERROR = "DOCUSIGN.INDIVIDUAL.CONTRACT_FILE_ERROR",
  INDIVIDUAL_CONTRACT_NOT_EXIST = "DOCUSIGN.INDIVIDUAL.CONTRACT_NOT_EXIST",
  /**
   * Corporate contract operations
   */
  CORPORATE_COMPANY_ID_REQUIRED = "DOCUSIGN.CORPORATE.COMPANY_ID_REQUIRED",
  CORPORATE_COMPANY_NOT_FOUND = "DOCUSIGN.CORPORATE.COMPANY_NOT_FOUND",
  CORPORATE_NO_SUPER_ADMIN_ID = "DOCUSIGN.CORPORATE.NO_SUPER_ADMIN_ID",
  CORPORATE_NO_SUPER_ADMIN_ROLE = "DOCUSIGN.CORPORATE.NO_SUPER_ADMIN_ROLE",
  CORPORATE_SIGNERS_NOT_FOUND = "DOCUSIGN.CORPORATE.SIGNERS_NOT_FOUND",
  CORPORATE_SIGNERS_NOT_SET = "DOCUSIGN.CORPORATE.SIGNERS_NOT_SET",
  CORPORATE_SIGNERS_NOT_FILLED = "DOCUSIGN.CORPORATE.SIGNERS_NOT_FILLED",
  CORPORATE_AT_LEAST_ONE_SIGNED = "DOCUSIGN.CORPORATE.AT_LEAST_ONE_SIGNED",
  CORPORATE_CONTRACT_NOT_EDITABLE = "DOCUSIGN.CORPORATE.CONTRACT_NOT_EDITABLE",
  /**
   * SDK operations
   */
  SDK_CONSENT_REQUIRED = "DOCUSIGN.SDK.CONSENT_REQUIRED",
  SDK_HTTP_ERROR = "DOCUSIGN.SDK.HTTP_ERROR",
  SDK_AUTH_ERROR = "DOCUSIGN.SDK.AUTH_ERROR",
  SDK_INCORRECT_FILE_FORMAT = "DOCUSIGN.SDK.INCORRECT_FILE_FORMAT",
}
