export const enum EContentManagementErrorCodes {
  /**
   * Promo operations
   */
  PROMO_ENGLISH_RECORD_REQUIRED = "CONTENT_MANAGEMENT.PROMO.ENGLISH_RECORD_REQUIRED",
  PROMO_IMAGE_REQUIRED_FOR_ENGLISH = "CONTENT_MANAGEMENT.PROMO.IMAGE_REQUIRED_FOR_ENGLISH",
  PROMO_DUPLICATE_ORDINAL_AND_LANGUAGE = "CONTENT_MANAGEMENT.PROMO.DUPLICATE_ORDINAL_AND_LANGUAGE",
  /**
   * Content management operations
   */
  CONTENT_NOT_FOUND = "CONTENT_MANAGEMENT.CONTENT.NOT_FOUND",
}
