export const enum EAccessControlErrorCodes {
  /**
   ** Authorization operations
   */
  ADMIN_ROLE_REQUIRED = "ACCESS_CONTROL.AUTHORIZATION.ADMIN_ROLE_REQUIRED",
  INSUFFICIENT_PRIVILEGES = "ACCESS_CONTROL.AUTHORIZATION.INSUFFICIENT_PRIVILEGES",
  /**
   ** Company operations
   */
  DIFFERENT_COMPANIES_ACCESS_DENIED = "ACCESS_CONTROL.COMPANY.DIFFERENT_COMPANIES_DENIED",
  COMPANY_ID_REQUIRED = "ACCESS_CONTROL.COMPANY.ID_REQUIRED",
}
