export const enum EAuthErrorCodes {
  /**
   ** Registration link operations
   */
  REGISTRATION_LINK_ALREADY_SENT = "AUTH.REGISTRATION_LINK.ALREADY_SENT",
  REGISTRATION_LINK_ALREADY_FINISHED = "AUTH.REGISTRATION_LINK.ALREADY_FINISHED",
  REGISTRATION_LINK_DELETION_NOT_ALLOWED = "AUTH.REGISTRATION_LINK.DELETION_NOT_ALLOWED",
  REGISTRATION_LINK_TIME_LIMIT_NOT_REACHED = "AUTH.REGISTRATION_LINK.TIME_LIMIT_NOT_REACHED",
  /**
   * Registration operations
   */
  REGISTRATION_EMAIL_NOT_AUTHORIZED = "AUTH.REGISTRATION.EMAIL_NOT_AUTHORIZED",
  REGISTRATION_EMAIL_ALREADY_EXISTS = "AUTH.REGISTRATION.EMAIL_ALREADY_EXISTS",
  REGISTRATION_EMAIL_ALREADY_VERIFIED = "AUTH.REGISTRATION.EMAIL_ALREADY_VERIFIED",
  REGISTRATION_PASSWORD_NOT_ALLOWED_OAUTH = "AUTH.REGISTRATION.PASSWORD_NOT_ALLOWED_OAUTH",
  REGISTRATION_ALREADY_FINISHED = "AUTH.REGISTRATION.ALREADY_FINISHED",
  REGISTRATION_EMAIL_NOT_VERIFIED = "AUTH.REGISTRATION.EMAIL_NOT_VERIFIED",
  REGISTRATION_PASSWORD_NOT_SET = "AUTH.REGISTRATION.PASSWORD_NOT_SET",
  REGISTRATION_PHONE_NOT_VERIFIED = "AUTH.REGISTRATION.PHONE_NOT_VERIFIED",
  REGISTRATION_TERMS_NOT_AGREED = "AUTH.REGISTRATION.TERMS_NOT_AGREED",
  REGISTRATION_LINK_EXPIRED = "AUTH.REGISTRATION.LINK_EXPIRED",
  /**
   * Third party operations
   */
  THIRD_PARTY_AUTH_ROLE_UNDETERMINED = "AUTH.THIRD_PARTY_AUTH.ROLE_UNDETERMINED",
  /**
   * Authorization operations
   */
  AUTHORIZATION_INVALID_REQUEST = "AUTH.AUTHORIZATION.INVALID_REQUEST",
  AUTHORIZATION_ROLE_ALREADY_ACTIVE = "AUTH.AUTHORIZATION.ROLE_ALREADY_ACTIVE",
  AUTHORIZATION_INVALID_CREDENTIALS = "AUTH.AUTHORIZATION.INVALID_CREDENTIALS",
  /**
   * Staging operations
   */
  STAGING_EMAIL_NOT_AUTHORIZED = "AUTH.STAGING.EMAIL_NOT_AUTHORIZED",
}
