export const enum EJobType {
  DEFAULT = "default",
  PROCESS_STRIPE_CANCEL_SUBSCRIPTIONS = "process-stripe-cancel-subscriptions",
  PROCESS_STRIPE_UPDATE_SUBSCRIPTIONS_PRICE = "process-stripe-update-subscriptions-price",
  PROCESS_NOTIFY_MEMBERSHIP_CHANGES = "process-notify-membership-changes",
  PROCESS_SUMSUB_WEBHOOK = "process-sumsub-webhook",
  PROCESS_DOCUSIGN_WEBHOOK = "process-docusign-webhook",
  PROCESS_STRIPE_WEBHOOK = "process-stripe-webhook",
  PROCESS_CLOSE_MEETING = "process-close-meeting",
  PROCESS_CHECK_IN_OUT_APPOINTMENT = "process-check-in-out-appointment",
  PROCESS_CLOSE_MEETING_WITHOUT_CLIENT_VISIT = "process-close-meeting-without-client-visit",
  PROCESS_PAYMENT_PRE_AUTHORIZATION = "process-payment-pre-authorization",
  PROCESS_PAYMENT_AUTHORIZATION_CANCEL = "process-payment-authorization-cancel",
  PROCESS_PAYMENT_CAPTURE = "process-payment-capture",
  PROCESS_PAYMENT_TRANSFER = "process-payment-transfer",
  PROCESS_PAY_IN_RECEIPT_PDF_GENERATION = "process-pay-in-receipt-pdf-generation",
  PROCESS_PAY_OUT_RECEIPT_PDF_GENERATION = "process-pay-out-receipt-pdf-generation",
  PROCESS_TAX_INVOICE_RECEIPT_PDF_GENERATION = "process-tax-invoice-receipt-pdf-generation",
  PROCESS_MEMBERSHIP_INVOICE_PDF_GENERATION = "process-membership-invoice-pdf-generation",
  PROCESS_INTERPRETER_BADGE_PDF_GENERATION = "process-interpreter-badge-pdf-generation",
  PROCESS_DEPOSIT_CHARGE_PDF_GENERATION = "process-deposit-charge-pdf-generation",
  PROCESS_CORPORATE_PAYOUT_RECEIPT_PDF_GENERATION = "process-corporate-payout-receipt-pdf-generation",
  PROCESS_CORPORATE_TAX_INVOICE_RECEIPT_PDF_GENERATION = "process-corporate-tax-invoice-receipt-pdf-generation",
}
