export const enum EChimeMeetingConfigurationErrorCodes {
  /**
   * Attendee creation service operations
   */
  ATTENDEE_CREATION_INVALID_COMMUNICATION_TYPE = "CHIME_MEETING_CONFIGURATION.ATTENDEE_CREATION.INVALID_COMMUNICATION_TYPE",
  /**
   * Attendee management service operations
   */
  ATTENDEE_MANAGEMENT_NO_ATTENDEES_FOUND = "CHIME_MEETING_CONFIGURATION.ATTENDEE_MANAGEMENT.NO_ATTENDEES_FOUND",
  ATTENDEE_MANAGEMENT_MAX_ANONYMOUS_GUESTS = "CHIME_MEETING_CONFIGURATION.ATTENDEE_MANAGEMENT.MAX_ANONYMOUS_GUESTS",
  ATTENDEE_MANAGEMENT_CANNOT_DISABLE_ADMIN_CLIENT = "CHIME_MEETING_CONFIGURATION.ATTENDEE_MANAGEMENT.CANNOT_DISABLE_ADMIN_CLIENT",
  ATTENDEE_MANAGEMENT_VIDEO_CAPABILITIES_NONE = "CHIME_MEETING_CONFIGURATION.ATTENDEE_MANAGEMENT.VIDEO_CAPABILITIES_NONE",
  ATTENDEE_MANAGEMENT_CONTENT_CAPABILITIES_NONE = "CHIME_MEETING_CONFIGURATION.ATTENDEE_MANAGEMENT.CONTENT_CAPABILITIES_NONE",
  ATTENDEE_MANAGEMENT_CANNOT_UPDATE_ADMIN = "CHIME_MEETING_CONFIGURATION.ATTENDEE_MANAGEMENT.CANNOT_UPDATE_ADMIN",
  ATTENDEE_MANAGEMENT_CANNOT_UPDATE_OWN = "CHIME_MEETING_CONFIGURATION.ATTENDEE_MANAGEMENT.CANNOT_UPDATE_OWN",
  ATTENDEE_MANAGEMENT_CANNOT_DISABLE_ADMIN = "CHIME_MEETING_CONFIGURATION.ATTENDEE_MANAGEMENT.CANNOT_DISABLE_ADMIN",
  ATTENDEE_MANAGEMENT_CANNOT_DISABLE_CLIENT = "CHIME_MEETING_CONFIGURATION.ATTENDEE_MANAGEMENT.CANNOT_DISABLE_CLIENT",
  ATTENDEE_MANAGEMENT_UNABLE_JOIN_MEETING = "CHIME_MEETING_CONFIGURATION.ATTENDEE_MANAGEMENT.UNABLE_JOIN_MEETING",
  /**
   * Meeting closing service operations
   */
  MEETING_CLOSING_UPDATE_ATTENDEE_FAILED = "CHIME_MEETING_CONFIGURATION.MEETING_CLOSING.UPDATE_ATTENDEE_FAILED",
  MEETING_CLOSING_MEETING_NOT_FOUND = "CHIME_MEETING_CONFIGURATION.MEETING_CLOSING.MEETING_NOT_FOUND",
  MEETING_CLOSING_UNABLE_CLOSE_MEETING = "CHIME_MEETING_CONFIGURATION.MEETING_CLOSING.UNABLE_CLOSE_MEETING",
  MEETING_CLOSING_INCOMPLETE_MEETING_INFO = "CHIME_MEETING_CONFIGURATION.MEETING_CLOSING.INCOMPLETE_MEETING_INFO",
  /**
   * Meeting creation service operations
   */
  MEETING_CREATION_INVALID_COMMUNICATION_TYPE = "CHIME_MEETING_CONFIGURATION.MEETING_CREATION.INVALID_COMMUNICATION_TYPE",
  /**
   * Meeting join service operations
   */
  MEETING_JOIN_FAILED_TO_JOIN = "CHIME_MEETING_CONFIGURATION.MEETING_JOIN.FAILED_TO_JOIN",
  MEETING_JOIN_MEETING_NOT_ACTIVE = "CHIME_MEETING_CONFIGURATION.MEETING_JOIN.MEETING_NOT_ACTIVE",
  MEETING_JOIN_NO_PERMISSION = "CHIME_MEETING_CONFIGURATION.MEETING_JOIN.NO_PERMISSION",
  MEETING_JOIN_SAME_DAY_REQUIRED = "CHIME_MEETING_CONFIGURATION.MEETING_JOIN.SAME_DAY_REQUIRED",
  MEETING_JOIN_FIVE_MINUTE_LIMIT = "CHIME_MEETING_CONFIGURATION.MEETING_JOIN.FIVE_MINUTE_LIMIT",
  MEETING_JOIN_UNABLE_CREATE_MEETING = "CHIME_MEETING_CONFIGURATION.MEETING_JOIN.UNABLE_CREATE_MEETING",
  MEETING_JOIN_UNABLE_CREATE_ATTENDEE = "CHIME_MEETING_CONFIGURATION.MEETING_JOIN.UNABLE_CREATE_ATTENDEE",
  MEETING_JOIN_CHIME_MEETING_ID_NOT_FOUND = "CHIME_MEETING_CONFIGURATION.MEETING_JOIN.CHIME_MEETING_ID_NOT_FOUND",
  MEETING_JOIN_UNABLE_JOIN_MEETING = "CHIME_MEETING_CONFIGURATION.MEETING_JOIN.UNABLE_JOIN_MEETING",
  /**
   * SIP media service operations
   */
  SIP_MEDIA_MEETING_NOT_STARTED = "CHIME_MEETING_CONFIGURATION.SIP_MEDIA.MEETING_NOT_STARTED",
  SIP_MEDIA_ATTENDEE_IDS_REQUIRED = "CHIME_MEETING_CONFIGURATION.SIP_MEDIA.ATTENDEE_IDS_REQUIRED",
  SIP_MEDIA_INVALID_CALL_TYPE = "CHIME_MEETING_CONFIGURATION.SIP_MEDIA.INVALID_CALL_TYPE",
  SIP_MEDIA_INTERPRETER_INFO_NOT_FOUND = "CHIME_MEETING_CONFIGURATION.SIP_MEDIA.INTERPRETER_INFO_NOT_FOUND",
  SIP_MEDIA_CLIENT_INFO_NOT_FOUND = "CHIME_MEETING_CONFIGURATION.SIP_MEDIA.CLIENT_INFO_NOT_FOUND",
  SIP_MEDIA_MAX_PSTN_CALLS_REACHED = "CHIME_MEETING_CONFIGURATION.SIP_MEDIA.MAX_PSTN_CALLS_REACHED",
}
