export enum EAppointmentErrorCodes {
  /**
   ** Cancellation operations
   */
  CANNOT_CANCEL_SINGLE_GROUP_APPOINTMENT = "APPOINTMENTS.CANCELLATION.CANNOT_CANCEL_SINGLE_GROUP_APPOINTMENT",
  NO_APPOINTMENTS_TO_CANCEL_IN_GROUP = "APPOINTMENTS.CANCELLATION.NO_APPOINTMENTS_TO_CANCEL_IN_GROUP",
  NOT_ASSIGNED_TO_GROUP_APPOINTMENTS = "APPOINTMENTS.CANCELLATION.NOT_ASSIGNED_TO_GROUP_APPOINTMENTS",
  /**
   ** Command operations
   */
  APPOINTMENT_CANNOT_BE_DELETED = "APPOINTMENTS.COMMAND.CANNOT_BE_DELETED",
  APPOINTMENT_CANNOT_BE_ARCHIVED = "APPOINTMENTS.COMMAND.CANNOT_BE_ARCHIVED",
  APPOINTMENT_MUST_BE_LIVE_FOR_LATE_NOTIFICATION = "APPOINTMENTS.COMMAND.MUST_BE_LIVE_FOR_LATE_NOTIFICATION",
  APPOINTMENT_ADMIN_INFO_NOT_FOUND = "APPOINTMENTS.COMMAND.ADMIN_INFO_NOT_FOUND",
  /**
   ** Creation operations
   */
  SCHEDULING_EXTRA_DAYS_EMPTY = "APPOINTMENTS.CREATION.SCHEDULING_EXTRA_DAYS_EMPTY",
  MISSING_TIMEZONE = "APPOINTMENTS.CREATION.MISSING_TIMEZONE",
  CLIENT_NOT_FOUND = "APPOINTMENTS.CREATION.CLIENT_NOT_FOUND",
  UNEXPECTED_ERROR_VIRTUAL = "APPOINTMENTS.CREATION.UNEXPECTED_ERROR_VIRTUAL",
  UNEXPECTED_ERROR_FACE_TO_FACE = "APPOINTMENTS.CREATION.UNEXPECTED_ERROR_FACE_TO_FACE",
  /**
   ** Extension operations
   */
  INVALID_DATA = "APPOINTMENTS.EXTENSION.INVALID_DATA",
  RATE_FOR_BUSINESS_EXTENSION_NOT_FOUND = "APPOINTMENTS.EXTENSION.RATE_FOR_BUSINESS_EXTENSION_NOT_FOUND",
  STANDARD_OR_AFTER_HOURS_RATE_NOT_FOUND = "APPOINTMENTS.EXTENSION.STANDARD_OR_AFTER_HOURS_RATE_NOT_FOUND",
  INVALID_APPOINTMENT_ID = "APPOINTMENTS.EXTENSION.INVALID_APPOINTMENT_ID",
  /**
   ** Rating operations
   */
  APPOINTMENT_CANNOT_BE_RATED = "APPOINTMENTS.RATING.CANNOT_BE_RATED",
  /**
   ** Recreation operations
   */
  FAILED_TO_CONSTRUCT_RECREATE_DTO = "APPOINTMENTS.RECREATION.FAILED_TO_CONSTRUCT_RECREATE_DTO",
  /**
   ** Update operations
   */
  APPOINTMENT_CANNOT_BE_UPDATED = "APPOINTMENTS.UPDATE.CANNOT_BE_UPDATED",
  OVERTIME_RATES_ONLY_FOR_PENDING = "APPOINTMENTS.UPDATE.OVERTIME_RATES_ONLY_FOR_PENDING",
}
