export const enum ELanguageDocCheckErrorCodes {
  /**
   * Common operations
   */
  COMMON_NO_UPLOADED_FILE = "LANGUAGE_DOC_CHECK.COMMON.NO_UPLOADED_FILE",
  COMMON_CHECK_IN_STATUS_PENDING = "LANGUAGE_DOC_CHECK.COMMON.STATUS_PENDING",
  /**
   * Upload operations
   */
  UPLOAD_NOT_ALLOWED = "LANGUAGE_DOC_CHECK.UPLOAD.UPLOAD_NOT_ALLOWED",
  /**
   * Removal operations
   */
  REMOVAL_STATUS_PENDING = "LANGUAGE_DOC_CHECK.REMOVAL.STATUS_PENDING",
  /**
   * Validation operations
   */
  VALIDATION_NATIVE_LANGUAGE_NOT_SET = "LANGUAGE_DOC_CHECK.VALIDATION.NATIVE_LANGUAGE_NOT_SET",
  VALIDATION_SAME_AS_NATIVE_LANGUAGE = "LANGUAGE_DOC_CHECK.VALIDATION.SAME_AS_NATIVE_LANGUAGE",
  VALIDATION_ALREADY_EXISTS_FOR_LANGUAGE = "LANGUAGE_DOC_CHECK.VALIDATION.ALREADY_EXISTS_FOR_LANGUAGE",
  VALIDATION_IELTS_CHECK_EXISTS = "LANGUAGE_DOC_CHECK.VALIDATION.IELTS_CHECK_EXISTS",
  VALIDATION_PTE_NUMBERS_EXIST = "LANGUAGE_DOC_CHECK.VALIDATION.PTE_NUMBERS_EXIST",
}
