export const enum EOldPaymentsErrorCodes {
  /*
   * Common operations
   */
  COUNTRY_NOT_FILLED = "PAYMENTS.COMMON.COUNTRY_NOT_FILLED",
  COMPANY_NOT_FOUND = "PAYMENTS.COMMON.COMPANY_NOT_FOUND",
  USER_ROLE_NOT_EXIST = "PAYMENTS.COMMON.USER_ROLE_NOT_EXIST",
  PAYMENT_INFO_NOT_FILLED = "PAYMENTS.COMMON.PAYMENT_INFO_NOT_FILLED",
  STRIPE_PAYMENT_INFO_NOT_FILLED = "PAYMENTS.COMMON.STRIPE_PAYMENT_INFO_NOT_FILLED",
  CURRENCY_MISMATCH = "PAYMENTS.COMMON.CURRENCY_MISMATCH",
  INCORRECT_PAYMENT_SYSTEM = "PAYMENTS.COMMON.INCORRECT_PAYMENT_SYSTEM",
  INCORRECT_PAYMENT_DIRECTION = "PAYMENTS.COMMON.INCORRECT_PAYMENT_DIRECTION",
  CLIENT_NOT_EXIST = "PAYMENTS.COMMON.CLIENT_NOT_EXIST",
  CLIENT_PROFILE_NOT_FILLED = "PAYMENTS.COMMON.CLIENT_PROFILE_NOT_FILLED",
  CLIENT_CONTACT_EMAIL_NOT_FILLED = "PAYMENTS.COMMON.CLIENT_CONTACT_EMAIL_NOT_FILLED",
  STRIPE_CARD_PAYMENT_INFO_NOT_FILLED = "PAYMENTS.COMMON.STRIPE_CARD_PAYMENT_INFO_NOT_FILLED",
  INCOMING_PAYMENT_NO_ITEMS = "PAYMENTS.COMMON.INCOMING_PAYMENT_NO_ITEMS",
  /*
   * General operations
   */
  INCORRECT_DATA = "PAYMENTS.GENERAL.INCORRECT_DATA",
  RECEIPT_NOT_EXIST = "PAYMENTS.GENERAL.RECEIPT_NOT_EXIST",
  CORPORATE_INTERPRETER_NO_COMPANY = "PAYMENTS.GENERAL.CORPORATE_INTERPRETER_NO_COMPANY",
  /*
   * Individual operations
   */
  PAYMENT_ALREADY_CAPTURED = "PAYMENTS.INDIVIDUAL.PAYMENT_ALREADY_CAPTURED",
  INTERPRETER_NOT_EXIST = "PAYMENTS.INDIVIDUAL.INTERPRETER_NOT_EXIST",
  INTERPRETER_PROFILE_NOT_FILLED = "PAYMENTS.INDIVIDUAL.INTERPRETER_PROFILE_NOT_FILLED",
  INTERPRETER_CONTACT_EMAIL_NOT_FILLED = "PAYMENTS.INDIVIDUAL.INTERPRETER_CONTACT_EMAIL_NOT_FILLED",
  OUTCOMING_PAYMENT_ALREADY_EXISTS = "PAYMENTS.INDIVIDUAL.OUTCOMING_PAYMENT_ALREADY_EXISTS",
  /*
   * Corporate operations
   */
  INCOMING_PAYMENT_ITEM_INCORRECT_STATUS = "PAYMENTS.CORPORATE.INCOMING_PAYMENT_ITEM_INCORRECT_STATUS",
  COMPANY_PAYMENT_INFO_NOT_FOUND = "PAYMENTS.CORPORATE.COMPANY_PAYMENT_INFO_NOT_FOUND",
  COMMISSION_RATE_NOT_SET = "PAYMENTS.CORPORATE.COMMISSION_RATE_NOT_SET",
  PAYPAL_PAYMENT_INFO_NOT_FILLED = "PAYMENTS.CORPORATE.PAYPAL_PAYMENT_INFO_NOT_FILLED",
  COMPANY_NO_SUPER_ADMIN_ID = "PAYMENTS.CORPORATE.COMPANY_NO_SUPER_ADMIN_ID",
  SUPER_ADMIN_ROLE_NOT_FOUND = "PAYMENTS.CORPORATE.SUPER_ADMIN_ROLE_NOT_FOUND",
}
