export const enum EAddressesErrorCodes {
  /**
   ** Address operations
   */
  ADDRESS_NOT_ASSOCIATED_WITH_APPOINTMENT = "ADDRESSES.ADDRESS.NOT_ASSOCIATED_WITH_APPOINTMENT",
  ADDRESS_CANNOT_BE_UPDATED = "ADDRESSES.ADDRESS.CANNOT_BE_UPDATED",
}
