import { ValuesOf } from "src/common/types";

export const EExtCountry = {
  AFGHANISTAN: "Afghanistan",
  ALBANIA: "Albania",
  ALGERIA: "Algeria",
  AMERICAN_SAMOA: "American Samoa",
  ANDORRA: "Andorra",
  ANGOLA: "Angola",
  ANGUILLA: "Anguilla",
  ANTARCTICA: "Antarctica",
  ANTIGUA_AND_BARBUDA: "Antigua & Barbuda",
  ARGENTINA: "Argentina",
  ARMENIA: "Armenia",
  ARUBA: "Aruba",
  ASCENSION_ISLAND: "Ascension Island",
  AUSTRALIA: "Australia",
  AUSTRIA: "Austria",
  AZERBAIJAN: "Azerbaijan",
  ALAND_ISLANDS: "Åland Islands",
  BAHAMAS: "Bahamas",
  BAHRAIN: "Bahrain",
  BANGLADESH: "Bangladesh",
  BARBADOS: "Barbados",
  BELARUS: "Belarus",
  BELGIUM: "Belgium",
  BELIZE: "Belize",
  BENIN: "Benin",
  BERMUDA: "Bermuda",
  BHUTAN: "Bhutan",
  BOLIVIA: "Bolivia",
  BOSNIA_AND_HERZEGOVINA: "Bosnia & Herzegovina",
  BOTSWANA: "Botswana",
  BOUVET_ISLAND: "Bouvet Island",
  BRAZIL: "Brazil",
  BRITISH_INDIAN_OCEAN_TERRITORY: "British Indian Ocean Territory",
  BRITISH_VIRGIN_ISLANDS: "British Virgin Islands",
  BRUNEI: "Brunei",
  BULGARIA: "Bulgaria",
  BURKINA_FASO: "Burkina Faso",
  BURUNDI: "Burundi",
  CAMBODIA: "Cambodia",
  CAMEROON: "Cameroon",
  CANADA: "Canada",
  CANARY_ISLANDS: "Canary Islands",
  CAPE_VERDE: "Cape Verde",
  CARIBBEAN_NETHERLANDS: "Caribbean Netherlands",
  CAYMAN_ISLANDS: "Cayman Islands",
  CENTRAL_AFRICAN_REPUBLIC: "Central African Republic",
  CEUTA_AND_MELILLA: "Ceuta & Melilla",
  CHAD: "Chad",
  CHILE: "Chile",
  CHINA: "China",
  CHRISTMAS_ISLAND: "Christmas Island",
  CLIPPERTON_ISLAND: "Clipperton Island",
  COCOS_KEELING_ISLANDS: "Cocos (Keeling) Islands",
  COLOMBIA: "Colombia",
  COMOROS: "Comoros",
  CONGO_BRAZZAVILLE: "Congo - Brazzaville",
  CONGO_KINSHASA: "Congo - Kinshasa",
  COOK_ISLANDS: "Cook Islands",
  COSTA_RICA: "Costa Rica",
  CROATIA: "Croatia",
  CUBA: "Cuba",
  CURACAO: "Curaçao",
  CYPRUS: "Cyprus",
  CZECHIA: "Czechia",
  COTE_D_IVOIRE: "Côte d’Ivoire",
  DENMARK: "Denmark",
  DIEGO_GARCIA: "Diego Garcia",
  DJIBOUTI: "Djibouti",
  DOMINICA: "Dominica",
  DOMINICAN_REPUBLIC: "Dominican Republic",
  ECUADOR: "Ecuador",
  EGYPT: "Egypt",
  EL_SALVADOR: "El Salvador",
  EQUATORIAL_GUINEA: "Equatorial Guinea",
  ERITREA: "Eritrea",
  ESTONIA: "Estonia",
  ESWATINI: "Eswatini",
  ETHIOPIA: "Ethiopia",
  FALKLAND_ISLANDS_ISLAS_MALVINAS: "Falkland Islands (Islas Malvinas)",
  FAROE_ISLANDS: "Faroe Islands",
  FIJI: "Fiji",
  FINLAND: "Finland",
  FRANCE: "France",
  FRENCH_GUIANA: "French Guiana",
  FRENCH_POLYNESIA: "French Polynesia",
  FRENCH_SOUTHERN_TERRITORIES: "French Southern Territories",
  GABON: "Gabon",
  GAMBIA: "Gambia",
  GEORGIA: "Georgia",
  GERMANY: "Germany",
  GHANA: "Ghana",
  GIBRALTAR: "Gibraltar",
  GREECE: "Greece",
  GREENLAND: "Greenland",
  GRENADA: "Grenada",
  GUADELOUPE: "Guadeloupe",
  GUAM: "Guam",
  GUATEMALA: "Guatemala",
  GUERNSEY: "Guernsey",
  GUINEA: "Guinea",
  GUINEA_BISSAU: "Guinea-Bissau",
  GUYANA: "Guyana",
  HAITI: "Haiti",
  HEARD_AND_MCDONALD_ISLANDS: "Heard & McDonald Islands",
  HONDURAS: "Honduras",
  HONG_KONG: "Hong Kong",
  HUNGARY: "Hungary",
  ICELAND: "Iceland",
  INDIA: "India",
  INDONESIA: "Indonesia",
  IRAN: "Iran",
  IRAQ: "Iraq",
  IRELAND: "Ireland",
  ISLE_OF_MAN: "Isle of Man",
  ISRAEL: "Israel",
  ITALY: "Italy",
  JAMAICA: "Jamaica",
  JAPAN: "Japan",
  JERSEY: "Jersey",
  JORDAN: "Jordan",
  KAZAKHSTAN: "Kazakhstan",
  KENYA: "Kenya",
  KIRIBATI: "Kiribati",
  KOSOVO: "Kosovo",
  KUWAIT: "Kuwait",
  KYRGYZSTAN: "Kyrgyzstan",
  LAOS: "Laos",
  LATVIA: "Latvia",
  LEBANON: "Lebanon",
  LESOTHO: "Lesotho",
  LIBERIA: "Liberia",
  LIBYA: "Libya",
  LIECHTENSTEIN: "Liechtenstein",
  LITHUANIA: "Lithuania",
  LUXEMBOURG: "Luxembourg",
  MACAO: "Macao",
  MADAGASCAR: "Madagascar",
  MALAWI: "Malawi",
  MALAYSIA: "Malaysia",
  MALDIVES: "Maldives",
  MALI: "Mali",
  MALTA: "Malta",
  MARSHALL_ISLANDS: "Marshall Islands",
  MARTINIQUE: "Martinique",
  MAURITANIA: "Mauritania",
  MAURITIUS: "Mauritius",
  MAYOTTE: "Mayotte",
  MEXICO: "Mexico",
  MICRONESIA: "Micronesia",
  MOLDOVA: "Moldova",
  MONACO: "Monaco",
  MONGOLIA: "Mongolia",
  MONTENEGRO: "Montenegro",
  MONTSERRAT: "Montserrat",
  MOROCCO: "Morocco",
  MOZAMBIQUE: "Mozambique",
  MYANMAR_BURMA: "Myanmar (Burma)",
  NAMIBIA: "Namibia",
  NAURU: "Nauru",
  NEPAL: "Nepal",
  NETHERLANDS: "Netherlands",
  NEW_CALEDONIA: "New Caledonia",
  NEW_ZEALAND: "New Zealand",
  NICARAGUA: "Nicaragua",
  NIGER: "Niger",
  NIGERIA: "Nigeria",
  NIUE: "Niue",
  NORFOLK_ISLAND: "Norfolk Island",
  NORTH_KOREA: "North Korea",
  NORTH_MACEDONIA: "North Macedonia",
  NORTHERN_MARIANA_ISLANDS: "Northern Mariana Islands",
  NORWAY: "Norway",
  OMAN: "Oman",
  PAKISTAN: "Pakistan",
  PALAU: "Palau",
  PALESTINE: "Palestine",
  PANAMA: "Panama",
  PAPUA_NEW_GUINEA: "Papua New Guinea",
  PARAGUAY: "Paraguay",
  PERU: "Peru",
  PHILIPPINES: "Philippines",
  PITCAIRN_ISLANDS: "Pitcairn Islands",
  POLAND: "Poland",
  PORTUGAL: "Portugal",
  PUERTO_RICO: "Puerto Rico",
  QATAR: "Qatar",
  ROMANIA: "Romania",
  RUSSIA: "Russia",
  RWANDA: "Rwanda",
  REUNION: "Réunion",
  SAMOA: "Samoa",
  SAN_MARINO: "San Marino",
  SAUDI_ARABIA: "Saudi Arabia",
  SENEGAL: "Senegal",
  SERBIA: "Serbia",
  SEYCHELLES: "Seychelles",
  SIERRA_LEONE: "Sierra Leone",
  SINGAPORE: "Singapore",
  SINT_MAARTEN: "Sint Maarten",
  SLOVAKIA: "Slovakia",
  SLOVENIA: "Slovenia",
  SOLOMON_ISLANDS: "Solomon Islands",
  SOMALIA: "Somalia",
  SOUTH_AFRICA: "South Africa",
  SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS: "South Georgia & South Sandwich Islands",
  SOUTH_KOREA: "South Korea",
  SOUTH_SUDAN: "South Sudan",
  SPAIN: "Spain",
  SRI_LANKA: "Sri Lanka",
  ST_BARTHELEMY: "St. Barthélemy",
  ST_HELENA: "St. Helena",
  ST_KITTS_AND_NEVIS: "St. Kitts & Nevis",
  ST_LUCIA: "St. Lucia",
  ST_MARTIN: "St. Martin",
  ST_PIERRE_AND_MIQUELON: "St. Pierre & Miquelon",
  ST_VINCENT_AND_GRENADINES: "St. Vincent & Grenadines",
  SUDAN: "Sudan",
  SURINAME: "Suriname",
  SVALBARD_AND_JAN_MAYEN: "Svalbard & Jan Mayen",
  SWEDEN: "Sweden",
  SWITZERLAND: "Switzerland",
  SYRIA: "Syria",
  SAO_TOME_AND_PRINCIPE: "São Tomé & Príncipe",
  TAIWAN: "Taiwan",
  TAJIKISTAN: "Tajikistan",
  TANZANIA: "Tanzania",
  THAILAND: "Thailand",
  TIMOR_LESTE: "Timor-Leste",
  TOGO: "Togo",
  TOKELAU: "Tokelau",
  TONGA: "Tonga",
  TRINIDAD_AND_TOBAGO: "Trinidad & Tobago",
  TRISTAN_DA_CUNHA: "Tristan da Cunha",
  TUNISIA: "Tunisia",
  TURKEY: "Turkey",
  TURKMENISTAN: "Turkmenistan",
  TURKS_AND_CAICOS_ISLANDS: "Turks & Caicos Islands",
  TUVALU: "Tuvalu",
  US_OUTLYING_ISLANDS: "U.S. Outlying Islands",
  US_VIRGIN_ISLANDS: "U.S. Virgin Islands",
  UGANDA: "Uganda",
  UKRAINE: "Ukraine",
  UNITED_ARAB_EMIRATES: "United Arab Emirates",
  UNITED_KINGDOM: "United Kingdom",
  UNITED_STATES: "United States",
  URUGUAY: "Uruguay",
  UZBEKISTAN: "Uzbekistan",
  VANUATU: "Vanuatu",
  VATICAN_CITY: "Vatican City",
  VENEZUELA: "Venezuela",
  VIETNAM: "Vietnam",
  WALLIS_AND_FUTUNA: "Wallis & Futuna",
  WESTERN_SAHARA: "Western Sahara",
  YEMEN: "Yemen",
  ZAMBIA: "Zambia",
  ZIMBABWE: "Zimbabwe",
} as const;

export type EExtCountry = ValuesOf<typeof EExtCountry>;

export const countryCodeMap = {
  AF: EExtCountry.AFGHANISTAN,
  AL: EExtCountry.ALBANIA,
  DZ: EExtCountry.ALGERIA,
  AS: EExtCountry.AMERICAN_SAMOA,
  AD: EExtCountry.ANDORRA,
  AO: EExtCountry.ANGOLA,
  AI: EExtCountry.ANGUILLA,
  AQ: EExtCountry.ANTARCTICA,
  AG: EExtCountry.ANTIGUA_AND_BARBUDA,
  AR: EExtCountry.ARGENTINA,
  AM: EExtCountry.ARMENIA,
  AW: EExtCountry.ARUBA,
  AC: EExtCountry.ASCENSION_ISLAND,
  AU: EExtCountry.AUSTRALIA,
  AT: EExtCountry.AUSTRIA,
  AZ: EExtCountry.AZERBAIJAN,
  AX: EExtCountry.ALAND_ISLANDS,
  BS: EExtCountry.BAHAMAS,
  BH: EExtCountry.BAHRAIN,
  BD: EExtCountry.BANGLADESH,
  BB: EExtCountry.BARBADOS,
  BY: EExtCountry.BELARUS,
  BE: EExtCountry.BELGIUM,
  BZ: EExtCountry.BELIZE,
  BJ: EExtCountry.BENIN,
  BM: EExtCountry.BERMUDA,
  BT: EExtCountry.BHUTAN,
  BO: EExtCountry.BOLIVIA,
  BA: EExtCountry.BOSNIA_AND_HERZEGOVINA,
  BW: EExtCountry.BOTSWANA,
  BV: EExtCountry.BOUVET_ISLAND,
  BR: EExtCountry.BRAZIL,
  IO: EExtCountry.BRITISH_INDIAN_OCEAN_TERRITORY,
  VG: EExtCountry.BRITISH_VIRGIN_ISLANDS,
  BN: EExtCountry.BRUNEI,
  BG: EExtCountry.BULGARIA,
  BF: EExtCountry.BURKINA_FASO,
  BI: EExtCountry.BURUNDI,
  KH: EExtCountry.CAMBODIA,
  CM: EExtCountry.CAMEROON,
  CA: EExtCountry.CANADA,
  IC: EExtCountry.CANARY_ISLANDS,
  CV: EExtCountry.CAPE_VERDE,
  BQ: EExtCountry.CARIBBEAN_NETHERLANDS,
  KY: EExtCountry.CAYMAN_ISLANDS,
  CF: EExtCountry.CENTRAL_AFRICAN_REPUBLIC,
  EA: EExtCountry.CEUTA_AND_MELILLA,
  TD: EExtCountry.CHAD,
  CL: EExtCountry.CHILE,
  CN: EExtCountry.CHINA,
  CX: EExtCountry.CHRISTMAS_ISLAND,
  CP: EExtCountry.CLIPPERTON_ISLAND,
  CC: EExtCountry.COCOS_KEELING_ISLANDS,
  CO: EExtCountry.COLOMBIA,
  KM: EExtCountry.COMOROS,
  CG: EExtCountry.CONGO_BRAZZAVILLE,
  CD: EExtCountry.CONGO_KINSHASA,
  CK: EExtCountry.COOK_ISLANDS,
  CR: EExtCountry.COSTA_RICA,
  HR: EExtCountry.CROATIA,
  CU: EExtCountry.CUBA,
  CW: EExtCountry.CURACAO,
  CY: EExtCountry.CYPRUS,
  CZ: EExtCountry.CZECHIA,
  CI: EExtCountry.COTE_D_IVOIRE,
  DK: EExtCountry.DENMARK,
  DG: EExtCountry.DIEGO_GARCIA,
  DJ: EExtCountry.DJIBOUTI,
  DM: EExtCountry.DOMINICA,
  DO: EExtCountry.DOMINICAN_REPUBLIC,
  EC: EExtCountry.ECUADOR,
  EG: EExtCountry.EGYPT,
  SV: EExtCountry.EL_SALVADOR,
  GQ: EExtCountry.EQUATORIAL_GUINEA,
  ER: EExtCountry.ERITREA,
  EE: EExtCountry.ESTONIA,
  SZ: EExtCountry.ESWATINI,
  ET: EExtCountry.ETHIOPIA,
  FL: EExtCountry.FALKLAND_ISLANDS_ISLAS_MALVINAS,
  FO: EExtCountry.FAROE_ISLANDS,
  FJ: EExtCountry.FIJI,
  FI: EExtCountry.FINLAND,
  FR: EExtCountry.FRANCE,
  GF: EExtCountry.FRENCH_GUIANA,
  PF: EExtCountry.FRENCH_POLYNESIA,
  TF: EExtCountry.FRENCH_SOUTHERN_TERRITORIES,
  GA: EExtCountry.GABON,
  GM: EExtCountry.GAMBIA,
  GE: EExtCountry.GEORGIA,
  DE: EExtCountry.GERMANY,
  GH: EExtCountry.GHANA,
  GI: EExtCountry.GIBRALTAR,
  GR: EExtCountry.GREECE,
  GL: EExtCountry.GREENLAND,
  GD: EExtCountry.GRENADA,
  GP: EExtCountry.GUADELOUPE,
  GU: EExtCountry.GUAM,
  GT: EExtCountry.GUATEMALA,
  GG: EExtCountry.GUERNSEY,
  GN: EExtCountry.GUINEA,
  GW: EExtCountry.GUINEA_BISSAU,
  GY: EExtCountry.GUYANA,
  HT: EExtCountry.HAITI,
  HM: EExtCountry.HEARD_AND_MCDONALD_ISLANDS,
  HN: EExtCountry.HONDURAS,
  HK: EExtCountry.HONG_KONG,
  HU: EExtCountry.HUNGARY,
  IS: EExtCountry.ICELAND,
  IN: EExtCountry.INDIA,
  ID: EExtCountry.INDONESIA,
  IR: EExtCountry.IRAN,
  IQ: EExtCountry.IRAQ,
  IE: EExtCountry.IRELAND,
  IM: EExtCountry.ISLE_OF_MAN,
  IL: EExtCountry.ISRAEL,
  IT: EExtCountry.ITALY,
  JM: EExtCountry.JAMAICA,
  JP: EExtCountry.JAPAN,
  JE: EExtCountry.JERSEY,
  JO: EExtCountry.JORDAN,
  KZ: EExtCountry.KAZAKHSTAN,
  KE: EExtCountry.KENYA,
  KI: EExtCountry.KIRIBATI,
  XK: EExtCountry.KOSOVO,
  KW: EExtCountry.KUWAIT,
  KG: EExtCountry.KYRGYZSTAN,
  LA: EExtCountry.LAOS,
  LV: EExtCountry.LATVIA,
  LB: EExtCountry.LEBANON,
  LS: EExtCountry.LESOTHO,
  LR: EExtCountry.LIBERIA,
  LY: EExtCountry.LIBYA,
  LI: EExtCountry.LIECHTENSTEIN,
  LT: EExtCountry.LITHUANIA,
  LU: EExtCountry.LUXEMBOURG,
  MO: EExtCountry.MACAO,
  MG: EExtCountry.MADAGASCAR,
  MW: EExtCountry.MALAWI,
  MY: EExtCountry.MALAYSIA,
  MV: EExtCountry.MALDIVES,
  ML: EExtCountry.MALI,
  MT: EExtCountry.MALTA,
  MH: EExtCountry.MARSHALL_ISLANDS,
  MQ: EExtCountry.MARTINIQUE,
  MR: EExtCountry.MAURITANIA,
  MU: EExtCountry.MAURITIUS,
  YT: EExtCountry.MAYOTTE,
  MX: EExtCountry.MEXICO,
  FM: EExtCountry.MICRONESIA,
  MD: EExtCountry.MOLDOVA,
  MC: EExtCountry.MONACO,
  MN: EExtCountry.MONGOLIA,
  ME: EExtCountry.MONTENEGRO,
  MS: EExtCountry.MONTSERRAT,
  MA: EExtCountry.MOROCCO,
  MZ: EExtCountry.MOZAMBIQUE,
  MM: EExtCountry.MYANMAR_BURMA,
  NA: EExtCountry.NAMIBIA,
  NR: EExtCountry.NAURU,
  NP: EExtCountry.NEPAL,
  NL: EExtCountry.NETHERLANDS,
  NC: EExtCountry.NEW_CALEDONIA,
  NZ: EExtCountry.NEW_ZEALAND,
  NI: EExtCountry.NICARAGUA,
  NE: EExtCountry.NIGER,
  NG: EExtCountry.NIGERIA,
  NU: EExtCountry.NIUE,
  NF: EExtCountry.NORFOLK_ISLAND,
  KP: EExtCountry.NORTH_KOREA,
  MK: EExtCountry.NORTH_MACEDONIA,
  MP: EExtCountry.NORTHERN_MARIANA_ISLANDS,
  NO: EExtCountry.NORWAY,
  OM: EExtCountry.OMAN,
  PK: EExtCountry.PAKISTAN,
  PW: EExtCountry.PALAU,
  PS: EExtCountry.PALESTINE,
  PA: EExtCountry.PANAMA,
  PG: EExtCountry.PAPUA_NEW_GUINEA,
  PY: EExtCountry.PARAGUAY,
  PE: EExtCountry.PERU,
  PH: EExtCountry.PHILIPPINES,
  PN: EExtCountry.PITCAIRN_ISLANDS,
  PL: EExtCountry.POLAND,
  PT: EExtCountry.PORTUGAL,
  PR: EExtCountry.PUERTO_RICO,
  QA: EExtCountry.QATAR,
  RO: EExtCountry.ROMANIA,
  RU: EExtCountry.RUSSIA,
  RW: EExtCountry.RWANDA,
  RE: EExtCountry.REUNION,
  WS: EExtCountry.SAMOA,
  SM: EExtCountry.SAN_MARINO,
  SA: EExtCountry.SAUDI_ARABIA,
  SN: EExtCountry.SENEGAL,
  RS: EExtCountry.SERBIA,
  SC: EExtCountry.SEYCHELLES,
  SL: EExtCountry.SIERRA_LEONE,
  SG: EExtCountry.SINGAPORE,
  SX: EExtCountry.SINT_MAARTEN,
  SK: EExtCountry.SLOVAKIA,
  SI: EExtCountry.SLOVENIA,
  SB: EExtCountry.SOLOMON_ISLANDS,
  SO: EExtCountry.SOMALIA,
  ZA: EExtCountry.SOUTH_AFRICA,
  GS: EExtCountry.SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS,
  KR: EExtCountry.SOUTH_KOREA,
  SS: EExtCountry.SOUTH_SUDAN,
  ES: EExtCountry.SPAIN,
  LK: EExtCountry.SRI_LANKA,
  BL: EExtCountry.ST_BARTHELEMY,
  SH: EExtCountry.ST_HELENA,
  KN: EExtCountry.ST_KITTS_AND_NEVIS,
  LC: EExtCountry.ST_LUCIA,
  MF: EExtCountry.ST_MARTIN,
  PM: EExtCountry.ST_PIERRE_AND_MIQUELON,
  VC: EExtCountry.ST_VINCENT_AND_GRENADINES,
  SD: EExtCountry.SUDAN,
  SR: EExtCountry.SURINAME,
  SJ: EExtCountry.SVALBARD_AND_JAN_MAYEN,
  SE: EExtCountry.SWEDEN,
  CH: EExtCountry.SWITZERLAND,
  SY: EExtCountry.SYRIA,
  ST: EExtCountry.SAO_TOME_AND_PRINCIPE,
  TW: EExtCountry.TAIWAN,
  TJ: EExtCountry.TAJIKISTAN,
  TZ: EExtCountry.TANZANIA,
  TH: EExtCountry.THAILAND,
  TL: EExtCountry.TIMOR_LESTE,
  TG: EExtCountry.TOGO,
  TK: EExtCountry.TOKELAU,
  TO: EExtCountry.TONGA,
  TT: EExtCountry.TRINIDAD_AND_TOBAGO,
  TA: EExtCountry.TRISTAN_DA_CUNHA,
  TN: EExtCountry.TUNISIA,
  TR: EExtCountry.TURKEY,
  TM: EExtCountry.TURKMENISTAN,
  TC: EExtCountry.TURKS_AND_CAICOS_ISLANDS,
  TV: EExtCountry.TUVALU,
  UM: EExtCountry.US_OUTLYING_ISLANDS,
  VI: EExtCountry.US_VIRGIN_ISLANDS,
  UG: EExtCountry.UGANDA,
  UA: EExtCountry.UKRAINE,
  AE: EExtCountry.UNITED_ARAB_EMIRATES,
  GB: EExtCountry.UNITED_KINGDOM,
  US: EExtCountry.UNITED_STATES,
  UY: EExtCountry.URUGUAY,
  UZ: EExtCountry.UZBEKISTAN,
  VU: EExtCountry.VANUATU,
  VA: EExtCountry.VATICAN_CITY,
  VE: EExtCountry.VENEZUELA,
  VN: EExtCountry.VIETNAM,
  WF: EExtCountry.WALLIS_AND_FUTUNA,
  EH: EExtCountry.WESTERN_SAHARA,
  YE: EExtCountry.YEMEN,
  ZM: EExtCountry.ZAMBIA,
  ZW: EExtCountry.ZIMBABWE,
} as const satisfies Record<string, EExtCountry>;

export const countryOrder = {
  [EExtCountry.AFGHANISTAN]: 1,
  [EExtCountry.ALBANIA]: 2,
  [EExtCountry.ALGERIA]: 3,
  [EExtCountry.AMERICAN_SAMOA]: 4,
  [EExtCountry.ANDORRA]: 5,
  [EExtCountry.ANGOLA]: 6,
  [EExtCountry.ANGUILLA]: 7,
  [EExtCountry.ANTARCTICA]: 8,
  [EExtCountry.ANTIGUA_AND_BARBUDA]: 9,
  [EExtCountry.ARGENTINA]: 10,
  [EExtCountry.ARMENIA]: 11,
  [EExtCountry.ARUBA]: 12,
  [EExtCountry.ASCENSION_ISLAND]: 13,
  [EExtCountry.AUSTRALIA]: 14,
  [EExtCountry.AUSTRIA]: 15,
  [EExtCountry.AZERBAIJAN]: 16,
  [EExtCountry.ALAND_ISLANDS]: 17,
  [EExtCountry.BAHAMAS]: 18,
  [EExtCountry.BAHRAIN]: 19,
  [EExtCountry.BANGLADESH]: 20,
  [EExtCountry.BARBADOS]: 21,
  [EExtCountry.BELARUS]: 22,
  [EExtCountry.BELGIUM]: 23,
  [EExtCountry.BELIZE]: 24,
  [EExtCountry.BENIN]: 25,
  [EExtCountry.BERMUDA]: 26,
  [EExtCountry.BHUTAN]: 27,
  [EExtCountry.BOLIVIA]: 28,
  [EExtCountry.BOSNIA_AND_HERZEGOVINA]: 29,
  [EExtCountry.BOTSWANA]: 30,
  [EExtCountry.BOUVET_ISLAND]: 31,
  [EExtCountry.BRAZIL]: 32,
  [EExtCountry.BRITISH_INDIAN_OCEAN_TERRITORY]: 33,
  [EExtCountry.BRITISH_VIRGIN_ISLANDS]: 34,
  [EExtCountry.BRUNEI]: 35,
  [EExtCountry.BULGARIA]: 36,
  [EExtCountry.BURKINA_FASO]: 37,
  [EExtCountry.BURUNDI]: 38,
  [EExtCountry.CAMBODIA]: 39,
  [EExtCountry.CAMEROON]: 40,
  [EExtCountry.CANADA]: 41,
  [EExtCountry.CANARY_ISLANDS]: 42,
  [EExtCountry.CAPE_VERDE]: 43,
  [EExtCountry.CARIBBEAN_NETHERLANDS]: 44,
  [EExtCountry.CAYMAN_ISLANDS]: 45,
  [EExtCountry.CENTRAL_AFRICAN_REPUBLIC]: 46,
  [EExtCountry.CEUTA_AND_MELILLA]: 47,
  [EExtCountry.CHAD]: 48,
  [EExtCountry.CHILE]: 49,
  [EExtCountry.CHINA]: 50,
  [EExtCountry.CHRISTMAS_ISLAND]: 51,
  [EExtCountry.CLIPPERTON_ISLAND]: 52,
  [EExtCountry.COCOS_KEELING_ISLANDS]: 53,
  [EExtCountry.COLOMBIA]: 54,
  [EExtCountry.COMOROS]: 55,
  [EExtCountry.CONGO_BRAZZAVILLE]: 56,
  [EExtCountry.CONGO_KINSHASA]: 57,
  [EExtCountry.COOK_ISLANDS]: 58,
  [EExtCountry.COSTA_RICA]: 59,
  [EExtCountry.CROATIA]: 60,
  [EExtCountry.CUBA]: 61,
  [EExtCountry.CURACAO]: 62,
  [EExtCountry.CYPRUS]: 63,
  [EExtCountry.CZECHIA]: 64,
  [EExtCountry.COTE_D_IVOIRE]: 65,
  [EExtCountry.DENMARK]: 66,
  [EExtCountry.DIEGO_GARCIA]: 67,
  [EExtCountry.DJIBOUTI]: 68,
  [EExtCountry.DOMINICA]: 69,
  [EExtCountry.DOMINICAN_REPUBLIC]: 70,
  [EExtCountry.ECUADOR]: 71,
  [EExtCountry.EGYPT]: 72,
  [EExtCountry.EL_SALVADOR]: 73,
  [EExtCountry.EQUATORIAL_GUINEA]: 74,
  [EExtCountry.ERITREA]: 75,
  [EExtCountry.ESTONIA]: 76,
  [EExtCountry.ESWATINI]: 77,
  [EExtCountry.ETHIOPIA]: 78,
  [EExtCountry.FALKLAND_ISLANDS_ISLAS_MALVINAS]: 79,
  [EExtCountry.FAROE_ISLANDS]: 80,
  [EExtCountry.FIJI]: 81,
  [EExtCountry.FINLAND]: 82,
  [EExtCountry.FRANCE]: 83,
  [EExtCountry.FRENCH_GUIANA]: 84,
  [EExtCountry.FRENCH_POLYNESIA]: 85,
  [EExtCountry.FRENCH_SOUTHERN_TERRITORIES]: 86,
  [EExtCountry.GABON]: 87,
  [EExtCountry.GAMBIA]: 88,
  [EExtCountry.GEORGIA]: 89,
  [EExtCountry.GERMANY]: 90,
  [EExtCountry.GHANA]: 91,
  [EExtCountry.GIBRALTAR]: 92,
  [EExtCountry.GREECE]: 93,
  [EExtCountry.GREENLAND]: 94,
  [EExtCountry.GRENADA]: 95,
  [EExtCountry.GUADELOUPE]: 96,
  [EExtCountry.GUAM]: 97,
  [EExtCountry.GUATEMALA]: 98,
  [EExtCountry.GUERNSEY]: 99,
  [EExtCountry.GUINEA]: 100,
  [EExtCountry.GUINEA_BISSAU]: 101,
  [EExtCountry.GUYANA]: 102,
  [EExtCountry.HAITI]: 103,
  [EExtCountry.HEARD_AND_MCDONALD_ISLANDS]: 104,
  [EExtCountry.HONDURAS]: 105,
  [EExtCountry.HONG_KONG]: 106,
  [EExtCountry.HUNGARY]: 107,
  [EExtCountry.ICELAND]: 108,
  [EExtCountry.INDIA]: 109,
  [EExtCountry.INDONESIA]: 110,
  [EExtCountry.IRAN]: 111,
  [EExtCountry.IRAQ]: 112,
  [EExtCountry.IRELAND]: 113,
  [EExtCountry.ISLE_OF_MAN]: 114,
  [EExtCountry.ISRAEL]: 115,
  [EExtCountry.ITALY]: 116,
  [EExtCountry.JAMAICA]: 117,
  [EExtCountry.JAPAN]: 118,
  [EExtCountry.JERSEY]: 119,
  [EExtCountry.JORDAN]: 120,
  [EExtCountry.KAZAKHSTAN]: 121,
  [EExtCountry.KENYA]: 122,
  [EExtCountry.KIRIBATI]: 123,
  [EExtCountry.KOSOVO]: 124,
  [EExtCountry.KUWAIT]: 125,
  [EExtCountry.KYRGYZSTAN]: 126,
  [EExtCountry.LAOS]: 127,
  [EExtCountry.LATVIA]: 128,
  [EExtCountry.LEBANON]: 129,
  [EExtCountry.LESOTHO]: 130,
  [EExtCountry.LIBERIA]: 131,
  [EExtCountry.LIBYA]: 132,
  [EExtCountry.LIECHTENSTEIN]: 133,
  [EExtCountry.LITHUANIA]: 134,
  [EExtCountry.LUXEMBOURG]: 135,
  [EExtCountry.MACAO]: 136,
  [EExtCountry.MADAGASCAR]: 137,
  [EExtCountry.MALAWI]: 138,
  [EExtCountry.MALAYSIA]: 139,
  [EExtCountry.MALDIVES]: 140,
  [EExtCountry.MALI]: 141,
  [EExtCountry.MALTA]: 142,
  [EExtCountry.MARSHALL_ISLANDS]: 143,
  [EExtCountry.MARTINIQUE]: 144,
  [EExtCountry.MAURITANIA]: 145,
  [EExtCountry.MAURITIUS]: 146,
  [EExtCountry.MAYOTTE]: 147,
  [EExtCountry.MEXICO]: 148,
  [EExtCountry.MICRONESIA]: 149,
  [EExtCountry.MOLDOVA]: 150,
  [EExtCountry.MONACO]: 151,
  [EExtCountry.MONGOLIA]: 152,
  [EExtCountry.MONTENEGRO]: 153,
  [EExtCountry.MONTSERRAT]: 154,
  [EExtCountry.MOROCCO]: 155,
  [EExtCountry.MOZAMBIQUE]: 156,
  [EExtCountry.MYANMAR_BURMA]: 157,
  [EExtCountry.NAMIBIA]: 158,
  [EExtCountry.NAURU]: 159,
  [EExtCountry.NEPAL]: 160,
  [EExtCountry.NETHERLANDS]: 161,
  [EExtCountry.NEW_CALEDONIA]: 162,
  [EExtCountry.NEW_ZEALAND]: 163,
  [EExtCountry.NICARAGUA]: 164,
  [EExtCountry.NIGER]: 165,
  [EExtCountry.NIGERIA]: 166,
  [EExtCountry.NIUE]: 167,
  [EExtCountry.NORFOLK_ISLAND]: 168,
  [EExtCountry.NORTH_KOREA]: 169,
  [EExtCountry.NORTH_MACEDONIA]: 170,
  [EExtCountry.NORTHERN_MARIANA_ISLANDS]: 171,
  [EExtCountry.NORWAY]: 172,
  [EExtCountry.OMAN]: 173,
  [EExtCountry.PAKISTAN]: 174,
  [EExtCountry.PALAU]: 175,
  [EExtCountry.PALESTINE]: 176,
  [EExtCountry.PANAMA]: 177,
  [EExtCountry.PAPUA_NEW_GUINEA]: 178,
  [EExtCountry.PARAGUAY]: 179,
  [EExtCountry.PERU]: 180,
  [EExtCountry.PHILIPPINES]: 181,
  [EExtCountry.PITCAIRN_ISLANDS]: 182,
  [EExtCountry.POLAND]: 183,
  [EExtCountry.PORTUGAL]: 184,
  [EExtCountry.PUERTO_RICO]: 185,
  [EExtCountry.QATAR]: 186,
  [EExtCountry.ROMANIA]: 187,
  [EExtCountry.RUSSIA]: 188,
  [EExtCountry.RWANDA]: 189,
  [EExtCountry.REUNION]: 190,
  [EExtCountry.SAMOA]: 191,
  [EExtCountry.SAN_MARINO]: 192,
  [EExtCountry.SAUDI_ARABIA]: 193,
  [EExtCountry.SENEGAL]: 194,
  [EExtCountry.SERBIA]: 195,
  [EExtCountry.SEYCHELLES]: 196,
  [EExtCountry.SIERRA_LEONE]: 197,
  [EExtCountry.SINGAPORE]: 198,
  [EExtCountry.SINT_MAARTEN]: 199,
  [EExtCountry.SLOVAKIA]: 200,
  [EExtCountry.SLOVENIA]: 201,
  [EExtCountry.SOLOMON_ISLANDS]: 202,
  [EExtCountry.SOMALIA]: 203,
  [EExtCountry.SOUTH_AFRICA]: 204,
  [EExtCountry.SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS]: 205,
  [EExtCountry.SOUTH_KOREA]: 206,
  [EExtCountry.SOUTH_SUDAN]: 207,
  [EExtCountry.SPAIN]: 208,
  [EExtCountry.SRI_LANKA]: 209,
  [EExtCountry.ST_BARTHELEMY]: 210,
  [EExtCountry.ST_HELENA]: 211,
  [EExtCountry.ST_KITTS_AND_NEVIS]: 212,
  [EExtCountry.ST_LUCIA]: 213,
  [EExtCountry.ST_MARTIN]: 214,
  [EExtCountry.ST_PIERRE_AND_MIQUELON]: 215,
  [EExtCountry.ST_VINCENT_AND_GRENADINES]: 216,
  [EExtCountry.SUDAN]: 217,
  [EExtCountry.SURINAME]: 218,
  [EExtCountry.SVALBARD_AND_JAN_MAYEN]: 219,
  [EExtCountry.SWEDEN]: 220,
  [EExtCountry.SWITZERLAND]: 221,
  [EExtCountry.SYRIA]: 222,
  [EExtCountry.SAO_TOME_AND_PRINCIPE]: 223,
  [EExtCountry.TAIWAN]: 224,
  [EExtCountry.TAJIKISTAN]: 225,
  [EExtCountry.TANZANIA]: 226,
  [EExtCountry.THAILAND]: 227,
  [EExtCountry.TIMOR_LESTE]: 228,
  [EExtCountry.TOGO]: 229,
  [EExtCountry.TOKELAU]: 230,
  [EExtCountry.TONGA]: 231,
  [EExtCountry.TRINIDAD_AND_TOBAGO]: 232,
  [EExtCountry.TRISTAN_DA_CUNHA]: 233,
  [EExtCountry.TUNISIA]: 234,
  [EExtCountry.TURKEY]: 235,
  [EExtCountry.TURKMENISTAN]: 236,
  [EExtCountry.TURKS_AND_CAICOS_ISLANDS]: 237,
  [EExtCountry.TUVALU]: 238,
  [EExtCountry.US_OUTLYING_ISLANDS]: 239,
  [EExtCountry.US_VIRGIN_ISLANDS]: 240,
  [EExtCountry.UGANDA]: 241,
  [EExtCountry.UKRAINE]: 242,
  [EExtCountry.UNITED_ARAB_EMIRATES]: 243,
  [EExtCountry.UNITED_KINGDOM]: 244,
  [EExtCountry.UNITED_STATES]: 245,
  [EExtCountry.URUGUAY]: 246,
  [EExtCountry.UZBEKISTAN]: 247,
  [EExtCountry.VANUATU]: 248,
  [EExtCountry.VATICAN_CITY]: 249,
  [EExtCountry.VENEZUELA]: 250,
  [EExtCountry.VIETNAM]: 251,
  [EExtCountry.WALLIS_AND_FUTUNA]: 252,
  [EExtCountry.WESTERN_SAHARA]: 253,
  [EExtCountry.YEMEN]: 254,
  [EExtCountry.ZAMBIA]: 255,
  [EExtCountry.ZIMBABWE]: 256,
} as const satisfies Record<EExtCountry, number>;
