export const enum ENaatiErrorCodes {
  /**
   * Web scraper operations
   */
  WEB_SCRAPER_HTTP_ERROR = "NAATI.WEB_SCRAPER.HTTP_ERROR",
  WEB_SCRAPER_NONCE_NOT_FOUND = "NAATI.WEB_SCRAPER.NONCE_NOT_FOUND",
  WEB_SCRAPER_NONCE_EXTRACTION_FAILED = "NAATI.WEB_SCRAPER.NONCE_EXTRACTION_FAILED",
  WEB_SCRAPER_API_ERROR = "NAATI.WEB_SCRAPER.API_ERROR",
  /**
   * Verification operations
   */
  VERIFICATION_INVALID_USER_STATUS = "NAATI.VERIFICATION.INVALID_USER_STATUS",
  VERIFICATION_INTERPRETER_NOT_FOUND = "NAATI.VERIFICATION.INTERPRETER_NOT_FOUND",
  VERIFICATION_PROFILE_NOT_FOUND = "NAATI.VERIFICATION.PROFILE_NOT_FOUND",
  VERIFICATION_CPN_ALREADY_SAVED = "NAATI.VERIFICATION.CPN_ALREADY_SAVED",
  VERIFICATION_INVALID_CPN = "NAATI.VERIFICATION.INVALID_CPN",
  VERIFICATION_NAME_MISMATCH = "NAATI.VERIFICATION.NAME_MISMATCH",
  VERIFICATION_LANGUAGE_NOT_SUPPORTED = "NAATI.VERIFICATION.LANGUAGE_NOT_SUPPORTED",
}
