import { ValuesOf } from "src/common/types";

export const EExtNaatiLanguages = {
  ACEH: "Aceh",
  ACHOLI: "Acholi",
  AFRIKAANS: "Afrikaans",
  ALBANIAN: "Albanian",
  ALYAWARR: "Alyawarr",
  AMHARIC: "Amharic",
  ANINDILYAKWA: "Anindilyakwa",
  ANMATYERR: "Anmatyerr",
  ARMENIAN: "Armenian",
  ASSYRIAN_NEO_ARAMAIC: "Assyrian Neo-Aramaic",
  BARI: "Bari",
  BASSA: "Bassa",
  BELARUSIAN: "Belarusian",
  BURARRA: "Burarra",
  BURMESE: "Burmese",
  CEBUANO: "Cebuano",
  CHALDEAN_NEO_ARAMAIC: "Chaldean Neo-Aramaic",
  COOK_ISLANDS_MAORI: "Cook Islands Maori",
  DANISH: "Danish",
  DINKA: "Dinka",
  DJAMBARRPUYNGU: "Djambarrpuyngu",
  DJAPU: "Djapu",
  DUTCH: "Dutch",
  DYIRBAL: "Dyirbal",
  CENTRAL_EASTERN_ARRENTE: "Central-Eastern Arrernte",
  KAYAH: "Kayah",
  ESTONIAN: "Estonian",
  FALAM_CHIN: "Falam Chin",
  FIJI_HINDI: "Fiji Hindi",
  FIJIAN: "Fijian",
  FULFULDE: "Fulfulde",
  FUR: "Fur",
  FUZHOU: "Fuzhou",
  GAJERRONG: "Gajerrong",
  GANDA: "Ganda",
  GARAWA: "Garawa",
  GEORGIAN: "Georgian",
  GUJARATI: "Gujarati",
  GUMATJ: "Gumatj",
  GUPAPUYNGU: "Gupapuyngu",
  HAKHA_CHIN: "Hakha Chin",
  HAKKA_CHINESE: "Hakka Chinese",
  HEBREW: "Hebrew",
  HINDUSTANI: "Hindustani",
  HIRI_MOTU: "Hiri Motu",
  HMONG: "Hmong",
  HOKKIEN: "Hokkien",
  IGBO: "Igbo",
  ICELANDIC: "Icelandic",
  IWAIDJA: "Iwaidja",
  JARU: "Jaru",
  KAKWA: "Kakwa",
  KALAW_KAWAW_YA: "Kalaw Kawaw Ya ",
  KARIYARRA: "Kariyarra",
  KAYTETYE: "Kaytetye",
  KHMER: "Khmer",
  KHUMI_CHIN: "Khumi Chin",
  KIJA: "Kija",
  KINYARWANDA: "Kinyarwanda",
  KIRUNDI: "Kirundi",
  KRIO: "Krio",
  KRIOL: "Kriol",
  FITZROY_VALLEY_KRIOL: "Fitzroy Valley Kriol",
  GURINDJI_KRIOL: "Gurindji Kriol",
  KIJA_KRIOL: "Kija Kriol",
  KIMBERLEY_KRIOL: "Kimberley Kriol",
  ROPER_RIVER_KRIOL: "Roper River Kriol",
  KUKATJA: "Kukatja",
  KUNWINJKU: "Kunwinjku",
  KURDISH_KURMANJI: "Kurdish Kurmanji",
  LAO: "Lao",
  LATVIAN: "Latvian",
  LIBERIAN_ENGLISH: "Liberian English",
  LINGALA: "Lingala",
  LITHUANIAN: "Lithuanian",
  LIYAGALAWUMIRR: "Liyagalawumirr",
  MADI: "Ma'di",
  MALAYALAM: "Malayalam",
  MALTESE: "Maltese",
  MANDINGO: "Mandingo",
  MARA_CHIN: "Mara Chin",
  MARATHI: "Marathi",
  MARTU_WANGKA: "Martu Wangka",
  MATU_CHIN: "Matu Chin",
  MELANESIAN_PIDGIN_ENGLISH: "Melanesian Pidgin English",
  MENDE: "Mende",
  MIN_NAN_CHINESE: "Min Nan Chinese",
  MIRIWOONG: "Miriwoong",
  MIZO_CHIN: "Mizo Chin",
  MODERN_TIWI: "Modern Tiwi",
  MONGOLIAN: "Mongolian",
  MOTU: "Motu",
  MURRINH_PATHA: "Murrinh-Patha",
  NEPALI: "Nepali",
  NGAANYATJARRA: "Ngaanyatjarra",
  NIGERIAN_PIDGIN: "Nigerian Pidgin",
  NORTH_AZERBAIJANI: "North Azerbaijani",
  NORWEGIAN: "Norwegian",
  NUER: "Nuer",
  NYANGUMARTA: "Nyangumarta",
  OROMO: "Oromo",
  PASHTO: "Pashto",
  PINTUPI_LURITJA: "Pintupi-Luritja",
  PITJANTJATJARA: "Pitjantjatjara",
  PUKAPUKAN: "Pukapukan",
  PULAAR: "Pulaar",
  PWO_EASTERN_KAREN: "Pwo Eastern Karen",
  ROHINGYA: "Rohingya",
  ROMANIAN: "Romanian",
  SAMOAN: "Samoan",
  SGAW_KAREN: "S'gaw Karen",
  SHANGHAINESE: "Shanghainese",
  SHILLUK: "Shilluk",
  SINDHI: "Sindhi",
  SLOVAK: "Slovak",
  SLOVENE: "Slovene",
  SOMALI: "Somali",
  KURDISH_SORANI: "Kurdish Sorani",
  SOUTH_AZERBAIJANI: "South Azerbaijani",
  KURDISH_SOUTHERN: "Kurdish Southern",
  SUNDANESE: "Sundanese",
  SWAHILI: "Swahili",
  SWATOW: "Swatow",
  SWEDISH: "Swedish",
  SYRIAC: "Syriac",
  TAIWANESE: "Taiwanese",
  TAMIL: "Tamil",
  TEDIM_CHIN: "Tedim Chin",
  TEOCHEW: "Teochew",
  TETUM: "Tetum",
  TIBETAN: "Tibetan",
  TIGRE: "Tigré",
  TIGRINYA: "Tigrinya",
  TONGAN: "Tongan",
  TRADITIONAL_TIWI: "Traditional Tiwi",
  TURKMEN: "Turkmen",
  UKRAINIAN: "Ukrainian",
  UYGHUR: "Uyghur",
  UZBEK: "Uzbek",
  WALMAJARRI: "Walmajarri",
  WANGKATHA: "Wangkatha",
  WARLPIRI: "Warlpiri",
  WARUMUNGU: "Warumungu",
  WESTERN_ARRARNTA: "Western Arrarnta",
  WIK_MUNGKAN: "Wik-Mungkan",
  YANKUNYTJATJARA: "Yankunytjatjara",
  YANYUWA: "Yanyuwa",
  YIDDISH: "Yiddish",
  YINDJIBARNDI: "Yindjibarndi",
  YUMPLATOK: "Yumplatok",
  ZANDE: "Zande",
  ZO: "Zo",
  ZOTUNG_CHIN: "Zotung Chin",
  ARABIC: "Arabic",
  BANGLA: "Bangla",
  BOSNIAN: "Bosnian",
  BULGARIAN: "Bulgarian",
  CANTONESE: "Cantonese",
  CROATIAN: "Croatian",
  CZECH: "Czech",
  DARI: "Dari",
  FILIPINO: "Filipino",
  FINNISH: "Finnish",
  FRENCH: "French",
  GERMAN: "German",
  GREEK: "Greek",
  HAZARAGI: "Hazaragi",
  HINDI: "Hindi",
  HUNGARIAN: "Hungarian",
  INDONESIAN: "Indonesian",
  ITALIAN: "Italian",
  JAPANESE: "Japanese",
  KOREAN: "Korean",
  MACEDONIAN: "Macedonian",
  MALAY: "Malay",
  MANDARIN: "Mandarin",
  PERSIAN: "Persian",
  POLISH: "Polish",
  PORTUGUESE: "Portuguese",
  PUNJABI: "Punjabi",
  RUSSIAN: "Russian",
  SERBIAN: "Serbian",
  SINHALESE: "Sinhalese",
  SPANISH: "Spanish",
  THAI: "Thai",
  TURKISH: "Turkish",
  URDU: "Urdu",
  VIETNAMESE: "Vietnamese",
  AFAR: "Afar",
  TOK_PISIN: "Tok Pisin",
  NUNGGUBUYU: "Nunggubuyu",
  MERIAM_MIR: "Meriam Mir",
  LURITJA: "Luritja",
  CHIU_CHOWN: "Chiu-Chownese",
  HASSANIYYA: "Hassaniyya",
  TELUGU: "Telugu",
  SHONA: "Shona",
  MAURITIAN_CREOLE: "Mauritian Creole",
  JUBA: "Juba",
  DZONGKHA: "Dzongkha",
  MONTENEGRIN: "Montenegrin",
  YORUBA: "Yoruba",
  TJUPAN: "Tjupan",
  DHUWAYA: "Dhuwaya",
  CHIN_MUUN: "Chin, Müün (Mindat)",
  AKAN_FANTI: "Akan (Fanti)",
  AKAN_TWI: "Akan (Twi)",
  SUDANESE_ARABIC: "Sudanese Arabic",
  CATALAN: "Catalan",
  HAITIAN_CREOLE: "Haitian Creole",
  SICILIAN: "Sicilian (alt Calabro-Sicilian)",
  BISLAMA: "Bislama",
  TE_REO_MAORI: "Te Reo Maori",
  SWAHILI_CONGO: "Swahili, Congo",
  ANUAK: "Anuak",
  KANNADA: "Kannada",
  EWE: "Éwé",
  ENGLISH: "English",
  PULAR: "Pular",
  TOKELAUAN: "Tokelauan",
  NIUE: "Niue",
  ROTUMAN: "Rotuman",
  PIJIN_SOLOMON_ISLANDS: "Pijin (Solomon Islands)",
  KIRIBATI: "Kiribati",
  TUVALUAN: "Tuvaluan",
  SANGO: "Sango",
  MON: "Mon",
  SIDAMO: "Sidamo",
  TAHITIAN: "Tahitian",
  DHIVEHI: "Dhivehi",
  TUROYO: "Turoyo",
  TAJIK: "Tajik",
  KAYAN: "Kayan",
  PUNJABI_WESTERN: "Punjabi (Western)",
  NAURUAN: "Nauruan",
  HARYANVI: "Haryanvi",
  XIANG: "Xiang",
  ILOCANO: "Ilocano",
  WU_CHINESE: "Wu Chinese",
  CHICHEWA: "Chichewa",
  NGARINYMAN: "Ngarinyman",
  ARABIC_CHADIAN: "Arabic, Chadian",
  MIN_DONG_CHINESE: "Min Dong Chinese",
  KUNAMA: "Kunama",
  SETSWANA: "Setswana",
  SOTHO_NORTHERN: "Sotho, Northern",
  GA: "Ga",
  MAWNG: "Mawng",
  SHAN: "Shan",

  /**
   ** Naati: Sign Languages - Interpreter
   */
  AUSLAN: "Auslan",
  AMERICAN_SIGN_LANGUAGE: "American Sign Language",
  NEW_ZEALAND_SIGN_LANGUAGE: "New Zealand Sign Language",
  INTERNATIONAL_SIGN_LANGUAGE: "International Sign Language",

  /**
   ** Naati: Sign Languages - Deaf Interpreting
   */
  DEAF_INTERPRETER: "Deaf Interpreter",
  ADAPTED_SIGN_LANGUAGE_AND_AUSLAN: "Adapted Sign Language and Auslan",
  AMERICAN_SIGN_LANGUAGE_AND_AUSLAN: "American Sign Language and Auslan",
  BHUTAN_SIGN_LANGUAGE_AND_AUSLAN: "Bhutanese Sign Language and Auslan",
  BRITISH_SIGN_LANGUAGE_AND_AUSLAN: "British Sign Language and Auslan",
  INTERNATIONAL_SIGN_LANGUAGE_AND_AUSLAN: "International Sign Language and Auslan",
  NEW_ZEALAND_SIGN_LANGUAGE_AND_AUSLAN: "New Zealand Sign Language and Auslan",
  NON_CONVENTIONAL_SIGN_LANGUAGE_AND_AUSLAN: "Non-Conventional Sign Language and Auslan",
  OTHER_CONVENTIONAL_SIGN_LANGUAGE_AND_AUSLAN: "Other Conventional Sign Language and Auslan",
  WRITTEN_ENGLISH_AND_AUSLAN: "Written English and Auslan",
  WRITTEN_ENGLISH_AND_NON_CONVENTIONAL_SIGN_LANGUAGE: "Written English and Non-Conventional Sign Language",
} as const;

export type EExtNaatiLanguages = ValuesOf<typeof EExtNaatiLanguages>;
