{
 "title": "Node.js Exporter Quickstart and Dashboard",
 "description": "A quickstart to setup the Prometheus Node.js Exporter with preconfigured dashboards, alerting rules, and recording rules.",
 "tags": [
  "node.js",
  "nodejs"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(nodejs_eventloop_lag_seconds, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nodejs_eventloop_lag_seconds, instance)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "User Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate of traffic ",
   "type": "timeseries",
   "description": "Rate of traffic 10 min",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Total Requests",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 2XX Status Code",
   "type": "stat",
   "description": "HTTP 2XX Status Code",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\",status_code=~\"2..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Distribution of Method ",
   "type": "piechart",
   "description": "Total Distribution of Method ",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\",}[$__range])) by (method) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Live Connections 🔴",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ws_connected_clients{job=~\"$job\", instance=~\"$instance\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Send Messages ✉️",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ws_messages_sent_total{job=~\"$job\", instance=~\"$instance\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 3XX Status Code",
   "type": "stat",
   "description": "HTTP 3XX Status Code",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\",status_code=~\"3..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 4XX Status Code",
   "type": "stat",
   "description": "HTTP 4XX Status Code",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\",status_code=~\"4..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5XX Status Code",
   "type": "stat",
   "description": "HTTP 5XX Status Code",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\",status_code=~\"5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Time of Live Connections",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ws_connection_duration_le_5{job=~\"$job\", instance=~\"$instance\",}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ws_connection_duration_le_15{job=~\"$job\", instance=~\"$instance\",}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ws_connection_duration_le_30{job=~\"$job\", instance=~\"$instance\",}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ws_connection_duration_le_60{job=~\"$job\", instance=~\"$instance\",}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ws_connection_duration_le_120{job=~\"$job\", instance=~\"$instance\",}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ws_connection_duration_le_300{job=~\"$job\", instance=~\"$instance\",}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ws_connection_duration_le_600{job=~\"$job\", instance=~\"$instance\",}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ws_connection_duration_le_900{job=~\"$job\", instance=~\"$instance\",}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ws_connection_duration_le_1800{job=~\"$job\", instance=~\"$instance\",}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_ws_connection_duration_gt_1800{job=~\"$job\", instance=~\"$instance\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Distribution of Requests by Endpoints for the Period",
   "type": "piechart",
   "description": "Total Distribution of Requests by Endpoints for the Period",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__range])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Node.js Version",
   "type": "stat",
   "description": "The version of Node.js.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "nodejs_version_info" }
   ]
  },
  {
   "title": "Node.js Restarts",
   "type": "stat",
   "description": "The number of times Node.js restarted.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{job=~\"$job\", instance=~\"$instance\",}[$__range]))",
     "legendFormat": "Node.js"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{job=~\"$job\", instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{job=~\"$job\", instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "System CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "Total CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Time Spent",
   "type": "timeseries",
   "description": "CPU time spent.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers and Requests",
   "type": "timeseries",
   "description": "Number of active handle and active requests.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Latency",
   "type": "timeseries",
   "description": "Latency of the event loop.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Last - {{instance}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "P99 - {{instance}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p50_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "P50 - {{instance}}"
    }
   ]
  },
  {
   "title": "Average Memory Used mb",
   "type": "heatmap",
   "description": "Average memory used in megabytes",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
   "targets": [
    {
     "expr": "avg(nodejs_external_memory_bytes{job=~\"$job\", instance=~\"$instance\",} / 1024 / 1024)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "GC Duration Rate",
   "type": "timeseries",
   "description": "Rate of garbage collection duration.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{kind}} - {{instance}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Duration of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{kind}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "description": "Usage of heap memory.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Used - {{instance}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Resident - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "External - {{instance}}"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "timeseries",
   "description": "Rate of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} - {{kind}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "description": "Count of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{kind}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Space Used",
   "type": "timeseries",
   "description": "Usage of heap space.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{space}} - {{instance}}"
    }
   ]
  }
 ]
}