export const enum ERatesErrorCodes {
  /*
   * Block Builder operations
   */
  ADDITIONAL_PRICES_REQUIRED = "RATES.BLOCK_BUILDER.ADDITIONAL_PRICES_REQUIRED",
  CROSS_BOUNDARY_ADDITIONAL_PRICES_REQUIRED = "RATES.BLOCK_BUILDER.CROSS_BOUNDARY_ADDITIONAL_PRICES_REQUIRED",
  /*
   * Config Validator operations
   */
  INTERPRETER_TYPE_REQUIRED = "RATES.CONFIG_VALIDATOR.INTERPRETER_TYPE_REQUIRED",
  SCHEDULING_TYPE_REQUIRED = "RATES.CONFIG_VALIDATOR.SCHEDULING_TYPE_REQUIRED",
  COMMUNICATION_TYPE_REQUIRED = "RATES.CONFIG_VALIDATOR.COMMUNICATION_TYPE_REQUIRED",
  INTERPRETING_TYPE_REQUIRED = "RATES.CONFIG_VALIDATOR.INTERPRETING_TYPE_REQUIRED",
  TOPIC_REQUIRED = "RATES.CONFIG_VALIDATOR.TOPIC_REQUIRED",
  DURATION_INVALID = "RATES.CONFIG_VALIDATOR.DURATION_INVALID",
  SCHEDULE_DATETIME_REQUIRED = "RATES.CONFIG_VALIDATOR.SCHEDULE_DATETIME_REQUIRED",
  ESCORT_SIMULTANEOUS_NOT_ALLOWED = "RATES.CONFIG_VALIDATOR.ESCORT_SIMULTANEOUS_NOT_ALLOWED",
  EXTRA_DAYS_NOT_ALLOWED_START_PRICE = "RATES.CONFIG_VALIDATOR.EXTRA_DAYS_NOT_ALLOWED_START_PRICE",
  CLIENT_GST_PAYER_REQUIRED_PRELIMINARY = "RATES.CONFIG_VALIDATOR.CLIENT_GST_PAYER_REQUIRED_PRELIMINARY",
  INTERPRETER_TIMEZONE_NOT_ALLOWED_PRELIMINARY = "RATES.CONFIG_VALIDATOR.INTERPRETER_TIMEZONE_NOT_ALLOWED_PRELIMINARY",
  CLIENT_TIMEZONE_NOT_ALLOWED_PRELIMINARY = "RATES.CONFIG_VALIDATOR.CLIENT_TIMEZONE_NOT_ALLOWED_PRELIMINARY",
  EXTERNAL_INTERPRETER_NOT_ALLOWED_PRELIMINARY = "RATES.CONFIG_VALIDATOR.EXTERNAL_INTERPRETER_NOT_ALLOWED_PRELIMINARY",
  DISCOUNTS_NOT_ALLOWED_PRELIMINARY = "RATES.CONFIG_VALIDATOR.DISCOUNTS_NOT_ALLOWED_PRELIMINARY",
  DISCOUNTS_MUST_BE_UNDEFINED_PRELIMINARY = "RATES.CONFIG_VALIDATOR.DISCOUNTS_MUST_BE_UNDEFINED_PRELIMINARY",
  EXTRA_DAYS_NOT_ALLOWED = "RATES.CONFIG_VALIDATOR.EXTRA_DAYS_NOT_ALLOWED",
  INTERPRETER_TIMEZONE_REQUIRED = "RATES.CONFIG_VALIDATOR.INTERPRETER_TIMEZONE_REQUIRED",
  CLIENT_TIMEZONE_REQUIRED = "RATES.CONFIG_VALIDATOR.CLIENT_TIMEZONE_REQUIRED",
  INTERPRETER_TIMEZONE_NOT_ALLOWED_PSTN = "RATES.CONFIG_VALIDATOR.INTERPRETER_TIMEZONE_NOT_ALLOWED_PSTN",
  CLIENT_TIMEZONE_REQUIRED_PSTN = "RATES.CONFIG_VALIDATOR.CLIENT_TIMEZONE_REQUIRED_PSTN",
  TIME_MODE_TIMEZONE_NOT_ALLOWED = "RATES.CONFIG_VALIDATOR.TIME_MODE_TIMEZONE_NOT_ALLOWED",
  TIMEZONES_NOT_ALLOWED_WITH_TIME_MODE = "RATES.CONFIG_VALIDATOR.TIMEZONES_NOT_ALLOWED_WITH_TIME_MODE",
  TIMEZONES_REQUIRED_AUTO_MODE = "RATES.CONFIG_VALIDATOR.TIMEZONES_REQUIRED_AUTO_MODE",
  PROMO_DISCOUNT_NEGATIVE = "RATES.CONFIG_VALIDATOR.PROMO_DISCOUNT_NEGATIVE",
  MEMBERSHIP_DISCOUNT_NEGATIVE = "RATES.CONFIG_VALIDATOR.MEMBERSHIP_DISCOUNT_NEGATIVE",
  MEMBERSHIP_FREE_MINUTES_NEGATIVE = "RATES.CONFIG_VALIDATOR.MEMBERSHIP_FREE_MINUTES_NEGATIVE",
  PROMO_DISCOUNT_MINUTES_NEGATIVE = "RATES.CONFIG_VALIDATOR.PROMO_DISCOUNT_MINUTES_NEGATIVE",
  /*
   * Rate Retriever operations
   */
  RATE_NOT_FOUND_ESCORT = "RATES.RETRIEVER.RATE_NOT_FOUND_ESCORT",
  RATES_NOT_FOUND = "RATES.RETRIEVER.RATES_NOT_FOUND",
  /*
   * Rate Step operations
   */
  INVALID_CALCULATION_TYPE = "RATES.STEP.INVALID_CALCULATION_TYPE",
  /*
   * Time Boundary Analyzer operations
   */
  UNHANDLED_DUAL_TIMEZONE_SCENARIO = "RATES.TIME_BOUNDARY.UNHANDLED_DUAL_TIMEZONE_SCENARIO",
}
