export const enum ECompaniesDepositChargeErrorCodes {
  /**
   * Company operations
   */
  COMPANY_NOT_FOUND = "COMPANIES_DEPOSIT_CHARGE.COMPANY.NOT_FOUND",
  COMPANY_NOT_ACTIVE = "COMPANIES_DEPOSIT_CHARGE.COMPANY.NOT_ACTIVE",
  COMPANY_NO_SUPER_ADMIN = "COMPANIES_DEPOSIT_CHARGE.COMPANY.NO_SUPER_ADMIN",
  /**
   * Charge operations
   */
  CHARGE_DEFAULT_AMOUNT_NOT_FILLED = "COMPANIES_DEPOSIT_CHARGE.CHARGE.DEFAULT_AMOUNT_NOT_FILLED",
  CHARGE_AMOUNT_ABOVE_MINIMUM = "COMPANIES_DEPOSIT_CHARGE.CHARGE.AMOUNT_ABOVE_MINIMUM",
  CHARGE_CANNOT_CHANGE_BEFORE_EXECUTION = "COMPANIES_DEPOSIT_CHARGE.CHARGE.CANNOT_CHANGE_BEFORE_EXECUTION",
  CHARGE_UNFINISHED_CHARGE_EXISTS = "COMPANIES_DEPOSIT_CHARGE.CHARGE.UNFINISHED_CHARGE_EXISTS",
  DEPOSIT_CHARGE_NOT_AVAILABLE_FOR_POST_PAYMENT = "COMPANIES_DEPOSIT_CHARGE.DEPOSIT_CHARGE_NOT_AVAILABLE_FOR_POST_PAYMENT",
  /**
   * Payment info operations
   */
  PAYMENT_INFO_NOT_FILLED = "COMPANIES_DEPOSIT_CHARGE.PAYMENT_INFO.NOT_FILLED",
  PAYMENT_INFO_STRIPE_NOT_FILLED = "COMPANIES_DEPOSIT_CHARGE.PAYMENT_INFO.STRIPE_NOT_FILLED",
  PAYMENT_INFO_ADMIN_EMAIL_NOT_FILLED = "COMPANIES_DEPOSIT_CHARGE.PAYMENT_INFO.ADMIN_EMAIL_NOT_FILLED",
  PAYMENT_INFO_ADMIN_INFO_NOT_FILLED = "COMPANIES_DEPOSIT_CHARGE.PAYMENT_INFO.ADMIN_INFO_NOT_FILLED",
  PAYMENT_INFO_SUPER_ADMIN_ROLE_NOT_FOUND = "COMPANIES_DEPOSIT_CHARGE.PAYMENT_INFO.SUPER_ADMIN_ROLE_NOT_FOUND",
}
