export const enum EPdfErrorCodes {
  /*
   * Builder operations
   */
  APPOINTMENT_NOT_EXIST = "PDF.BUILDER.APPOINTMENT_NOT_EXIST",
  APPOINTMENT_CLIENT_NOT_EXIST = "PDF.BUILDER.APPOINTMENT_CLIENT_NOT_EXIST",
  PAYMENT_COMPANY_NOT_EXIST = "PDF.BUILDER.PAYMENT_COMPANY_NOT_EXIST",
  PAYMENT_INFO_NOT_FILLED = "PDF.BUILDER.PAYMENT_INFO_NOT_FILLED",
  CLIENT_ADDRESS_NOT_FILLED = "PDF.BUILDER.CLIENT_ADDRESS_NOT_FILLED",
  PAYMENT_NO_APPOINTMENT = "PDF.BUILDER.PAYMENT_NO_APPOINTMENT",
  APPOINTMENT_INTERPRETER_NOT_FILLED = "PDF.BUILDER.APPOINTMENT_INTERPRETER_NOT_FILLED",
  INTERPRETER_PROFILE_NOT_FILLED = "PDF.BUILDER.INTERPRETER_PROFILE_NOT_FILLED",
  INTERPRETER_ADDRESS_NOT_FILLED = "PDF.BUILDER.INTERPRETER_ADDRESS_NOT_FILLED",
  INTERPRETER_ABN_NOT_FILLED = "PDF.BUILDER.INTERPRETER_ABN_NOT_FILLED",
  APPOINTMENT_BUSINESS_END_TIME_NOT_FILLED = "PDF.BUILDER.APPOINTMENT_BUSINESS_END_TIME_NOT_FILLED",
  COMPANY_LFH_DATA_NOT_SEEDED = "PDF.BUILDER.COMPANY_LFH_DATA_NOT_SEEDED",
  INSUFFICIENT_DATA_FOR_BADGE = "PDF.BUILDER.INSUFFICIENT_DATA_FOR_BADGE",
  COMPANY_CLIENT_NOT_EXIST = "PDF.BUILDER.COMPANY_CLIENT_NOT_EXIST",
  /*
   * Base64 operations
   */
  IMAGE_FETCH_FAILED = "PDF.BASE64.IMAGE_FETCH_FAILED",
  IMAGE_CONVERSION_ERROR = "PDF.BASE64.IMAGE_CONVERSION_ERROR",
}
