export const enum EArchiveAudioRecordsErrorCodes {
  /**
   ** Recording operations
   */
  RECORDING_KEY_NOT_FOUND = "ARCHIVE_AUDIO_RECORD.RECORDING.KEY_NOT_FOUND",
  FILE_RESTORE_IN_PROGRESS = "ARCHIVE_AUDIO_RECORD.RECORDING.FILE_RESTORE_IN_PROGRESS",
  FILE_KEY_UNDEFINED = "ARCHIVE_AUDIO_RECORD.RECORDING.FILE_KEY_UNDEFINED",
  FILE_COUNT_ISSUE = "ARCHIVE_AUDIO_RECORD.RECORDING.FILE_COUNT_ISSUE",
}
