export const enum EAppointmentOrderErrorCodes {
  /**
   ** Command operations
   */
  CLIENT_NOT_FOUND_FOR_ORDER = "APPOINTMENT_ORDER.COMMAND.CLIENT_NOT_FOUND_FOR_ORDER",
  CANNOT_ACCEPT_SINGLE_ORDER = "APPOINTMENT_ORDER.COMMAND.CANNOT_ACCEPT_SINGLE_ORDER",
  NO_ORDERS_FOUND_IN_GROUP = "APPOINTMENT_ORDER.COMMAND.NO_ORDERS_FOUND_IN_GROUP",
  ON_DEMAND_NOT_REPEATABLE = "APPOINTMENT_ORDER.COMMAND.ON_DEMAND_NOT_REPEATABLE",
  INTERPRETER_NOT_IN_ORDER = "APPOINTMENT_ORDER.COMMAND.INTERPRETER_NOT_IN_ORDER",
  TIME_ALREADY_RESERVED = "APPOINTMENT_ORDER.COMMAND.TIME_ALREADY_RESERVED",
  /**
   ** Expiration operations
   */
  CLIENT_NOT_FOUND_FOR_APPOINTMENT = "APPOINTMENT_ORDER.EXPIRATION.CLIENT_NOT_FOUND_FOR_APPOINTMENT",
  ENTITY_MISSING_FOR_APPOINTMENT = "APPOINTMENT_ORDER.EXPIRATION.ENTITY_MISSING_FOR_APPOINTMENT",
  ENTITIES_NOT_FOUND_FOR_DELETION = "APPOINTMENT_ORDER.EXPIRATION.ENTITIES_NOT_FOUND_FOR_DELETION",
  /**
   ** Interpreter addition operations
   */
  ON_DEMAND_NO_INTERPRETER_ADDITION = "APPOINTMENT_ORDER.INTERPRETER_ADDITION.ON_DEMAND_NO_INTERPRETER_ADDITION",
  /**
   ** Query operations
   */
  INTERPRETER_ROLE_ID_REQUIRED = "APPOINTMENT_ORDER.QUERY.INTERPRETER_ROLE_ID_REQUIRED",
  INTERPRETERS_LIST_NOT_FOUND_FOR_APPOINTMENT = "APPOINTMENT_ORDER.QUERY.INTERPRETERS_LIST_NOT_FOUND_FOR_APPOINTMENT",
  INTERPRETERS_LIST_NOT_FOUND_FOR_GROUP = "APPOINTMENT_ORDER.QUERY.INTERPRETERS_LIST_NOT_FOUND_FOR_GROUP",
  /**
   ** Scheduler operations
   */
  REPEAT_INTERVAL_NOT_SET = "APPOINTMENT_ORDER.SCHEDULER.REPEAT_INTERVAL_NOT_SET",
  REMAINING_REPEATS_NOT_SET = "APPOINTMENT_ORDER.SCHEDULER.REMAINING_REPEATS_NOT_SET",
}
