export const enum EBlacklistErrorCodes {
  /**
   * Blacklist service operations
   */
  SERVICE_BLACKLIST_ALREADY_EXISTS = "BLACKLIST.SERVICE.BLACKLIST_ALREADY_EXISTS",
  SERVICE_CLIENT_OR_INTERPRETER_MISSING = "BLACKLIST.SERVICE.CLIENT_OR_INTERPRETER_MISSING",
  SERVICE_BLACKLIST_NOT_FOUND = "BLACKLIST.SERVICE.BLACKLIST_NOT_FOUND",
}
