export const enum EWebSocketEventTypes {
  EXCEPTION = "exception",
  NEW_APPOINTMENT_ORDERS = "new-appointment-orders",
  NEW_APPOINTMENT_ORDERS_GROUPS = "new-appointment-orders-groups",
  NEW_APPOINTMENTS = "new-appointments",
  NEW_APPOINTMENT_GROUPS = "new-appointment-groups",
  RED_FLAG_APPOINTMENTS = "red-flag-appointments",
  RED_FLAG_APPOINTMENT_GROUPS = "red-flag-appointment-groups",
  LIVE_SESSIONS = "live-sessions",
  CHANNEL_MESSAGE = "channel-message",
  CHANNEL_DELETE_MESSAGE = "channel-delete-message",
  RESET_ACTIVE_CHANNEL = "reset-active-channel",
  NEW_PRIVATE_CHANNELS = "new-private-channels",
  NEW_SUPPORT_CHANNELS = "new-support-channels",
  UPDATE_INTERPRETER_LOCATION = "update-interpreter-location",
  SIDEBAR_MESSAGES = "sidebar-messages",
  ON_DEMAND_APPOINTMENT_STATUS_UPDATE = "on-demand-appointment-status-update",
}
