export const enum EAbnErrorCodes {
  /**
   ** Check operations - retrieving ABN records
   */
  ABN_CHECK_NOT_FOUND = "ABN.CHECK.NOT_FOUND",
  /**
   ** User operations
   */
  USER_NOT_FOUND = "ABN.USER.NOT_FOUND",
  USER_ROLE_INVALID_STATUS = "ABN.USER.INVALID_STATUS",
  USER_NOT_EXIST = "ABN.USER.NOT_EXIST",
  /**
   ** Company operations
   */
  COMPANY_NOT_FOUND = "ABN.COMPANY.NOT_FOUND",
  COMPANY_INVALID_STATUS = "ABN.COMPANY.INVALID_STATUS",
  /**
   ** Verification operations
   */
  VERIFICATION_INVALID_NUMBER = "ABN.VERIFICATION.INVALID_NUMBER",
  VERIFICATION_CANCELLED = "ABN.VERIFICATION.CANCELLED",
  VERIFICATION_NAME_MISMATCH = "ABN.VERIFICATION.NAME_MISMATCH",
  VERIFICATION_COMPANY_MISMATCH = "ABN.VERIFICATION.COMPANY_MISMATCH",
  VERIFICATION_SERVICE_UNAVAILABLE = "ABN.VERIFICATION.SERVICE_UNAVAILABLE",
  /**
   ** Permission operations
   */
  PERMISSION_DENIED_CREATE_UPDATE = "ABN.PERMISSION.CREATE_UPDATE_DENIED",
  /**
   ** Delete operations
   */
  DELETE_NOT_FOUND = "ABN.DELETE.NOT_FOUND",
}
