export const enum EInterpretersProfileErrorCodes {
  /**
   * Profile operations
   */
  PROFILE_AUSTRALIA_NZ_ONLY = "INTERPRETERS_PROFILE.PROFILE.AUSTRALIA_NZ_ONLY",
  PROFILE_NOT_FOUND = "INTERPRETERS_PROFILE.PROFILE.NOT_FOUND",
  PROFILE_LOCATION_UPDATE_FAILED = "INTERPRETERS_PROFILE.PROFILE.LOCATION_UPDATE_FAILED",
  PROFILE_INVALID_INTERPRETER_ID = "INTERPRETERS_PROFILE.PROFILE.INVALID_INTERPRETER_ID",
  PROFILE_WWCC_REQUIRED = "INTERPRETERS_PROFILE.PROFILE.WWCC_REQUIRED",
  /**
   * Cancellation record operations
   */
  CANCELLATION_RECORD_NOT_FOUND = "INTERPRETERS_PROFILE.CANCELLATION_RECORD.NOT_FOUND",
}
