export const enum EInterpreterQuestionnaireErrorCodes {
  /**
   * Common operations
   */
  COMMON_QUESTIONNAIRE_NOT_FOUND = "INTERPRETERS_QUESTIONNAIRE.COMMON.QUESTIONNAIRE_NOT_FOUND",
  /**
   * Questionnaire operations
   */
  QUESTIONNAIRE_ALREADY_CREATED = "INTERPRETERS_QUESTIONNAIRE.QUESTIONNAIRE.ALREADY_CREATED",
  /**
   * Recommendations operations
   */
  RECOMMENDATIONS_QUESTIONNAIRE_NOT_FOUND = "INTERPRETERS_QUESTIONNAIRE.RECOMMENDATIONS.QUESTIONNAIRE_NOT_FOUND",
  RECOMMENDATIONS_RECOMMENDATION_NOT_FOUND = "INTERPRETERS_QUESTIONNAIRE.RECOMMENDATIONS.RECOMMENDATION_NOT_FOUND",
}
