export const enum ENotificationDataType {
  TEXT_INFO = "text-info",
  WWCC_VERIFICATION = "wwcc-verification",
  RIGHT_TO_WORK_VERIFICATION = "right-to-work-verification",
  LANGUAGE_DOCS_VERIFICATION = "language-docs-verification",
  CONCESSION_CARD_VERIFICATION = "concession-card-verification",
  ACCOUNT_ACTIVATION = "account-activation",
  ACCOUNT_DEACTIVATION = "account-deactivation",
  APPOINTMENT_ORDER_INVITATION = "appointment-order-invitation",
  ON_DEMAND_INVITATION = "on-demand-invitation",
  CANCEL_ON_DEMAND_INVITATION = "cancel-on-demand-invitation",
  SEARCH_ENGINE = "search-engine",
  DRAFT_APPOINTMENT_DETAILS = "draft-appointment-details",
  APPOINTMENT_DETAILS = "appointment-details",
  RED_FLAG_DETAILS = "red-flag-details",
  AVATAR_VERIFICATION = "avatar-verification",
  CHAT_MESSAGE = "chat-message",
  APPOINTMENT_ENDING_SOON = "appointment-ending-soon",
  APPOINTMENT_PAYMENT_SUCCEEDED = "appointment-payment-succeeded",
  APPOINTMENT_PAYMENT_FAILED = "appointment-payment-failed",
  INCORRECT_PAYMENT_INFORMATION = "incorrect-payment-information",
  DEPOSIT_CHARGE_SUCCEEDED = "deposit-charge-succeeded",
  DEPOSIT_CHARGE_FAILED = "deposit-charge-failed",
}
