export const enum EChimeMessagingConfigurationErrorCodes {
  /**
   * Creation operations
   */
  MESSAGING_CREATION_RECIPIENT_ID_REQUIRED = "CHIME_MESSAGING_CONFIGURATION.CREATION.RECIPIENT_ID_REQUIRED",
  MESSAGING_CREATION_ADMIN_RECIPIENT_SAME = "CHIME_MESSAGING_CONFIGURATION.CREATION.ADMIN_RECIPIENT_SAME",
  MESSAGING_CREATION_ADMIN_OR_USER_PROFILE_NOT_COMPLETED = "CHIME_MESSAGING_CONFIGURATION.CREATION.ADMIN_OR_USER_PROFILE_NOT_COMPLETED",
  MESSAGING_CREATION_USER_PROFILE_NOT_COMPLETED = "CHIME_MESSAGING_CONFIGURATION.CREATION.USER_PROFILE_NOT_COMPLETED",
  MESSAGING_CREATION_USER_INSTANCE_ARN_NOT_FOUND = "CHIME_MESSAGING_CONFIGURATION.CREATION.USER_INSTANCE_ARN_NOT_FOUND",
  /**
   * Identity operations
   */
  MESSAGING_IDENTITY_CREATE_APP_INSTANCE_FAILED = "CHIME_MESSAGING_CONFIGURATION.IDENTITY.CREATE_APP_INSTANCE_FAILED",
  /**
   * Management operations
   */
  MESSAGING_MANAGEMENT_USER_PROFILE_NOT_COMPLETED = "CHIME_MESSAGING_CONFIGURATION.MANAGEMENT.USER_PROFILE_NOT_COMPLETED",
  MESSAGING_MANAGEMENT_USER_ALREADY_MEMBER = "CHIME_MESSAGING_CONFIGURATION.MANAGEMENT.USER_ALREADY_MEMBER",
  MESSAGING_MANAGEMENT_CHANNEL_MAX_PARTICIPANTS = "CHIME_MESSAGING_CONFIGURATION.MANAGEMENT.CHANNEL_MAX_PARTICIPANTS",
  MESSAGING_MANAGEMENT_CHANNEL_UPDATE_FAILED = "CHIME_MESSAGING_CONFIGURATION.MANAGEMENT.CHANNEL_UPDATE_FAILED",
  MESSAGING_MANAGEMENT_DELETE_MESSAGE_FAILED = "CHIME_MESSAGING_CONFIGURATION.MANAGEMENT.DELETE_MESSAGE_FAILED",
  /**
   * Query operations
   */
  MESSAGING_QUERY_NO_APPOINTMENT_INFO = "CHIME_MESSAGING_CONFIGURATION.QUERY.NO_APPOINTMENT_INFO",
}
