export const enum EAwsS3ErrorCodes {
  /**
   * S3 operations
   */
  S3_FILES_NOT_FOUND = "AWS.S3.FILES_NOT_FOUND",
  S3_GET_SIGNED_URL_FAILED = "AWS.S3.GET_SIGNED_URL_FAILED",
  S3_RESTORE_OBJECT_FAILED = "AWS.S3.RESTORE_OBJECT_FAILED",
  S3_UPLOAD_OBJECT_FAILED = "AWS.S3.UPLOAD_OBJECT_FAILED",
  S3_GET_OBJECT_LIST_FAILED = "AWS.S3.GET_OBJECT_LIST_FAILED",
  S3_DELETE_OBJECT_FAILED = "AWS.S3.DELETE_OBJECT_FAILED",
  S3_DELETE_OBJECTS_FAILED = "AWS.S3.DELETE_OBJECTS_FAILED",
  S3_COPY_OBJECT_FAILED = "AWS.S3.COPY_OBJECT_FAILED",
}
