export const enum EConcessionCardErrorCodes {
  /**
   * Common validations
   */
  COMMON_SET_ONE_CARD_TYPE = "CONCESSION_CARD.COMMON.SET_ONE_CARD_TYPE",
  COMMON_REQUEST_PENDING = "CONCESSION_CARD.COMMON.REQUEST_PENDING",
  COMMON_NO_UPLOADED_FILE = "CONCESSION_CARD.COMMON.NO_UPLOADED_FILE",
  /**
   * Creation operations
   */
  CREATION_ALREADY_CREATED = "CONCESSION_CARD.CREATION.ALREADY_CREATED",
  CREATION_ALREADY_EXISTS = "CONCESSION_CARD.CREATION.ALREADY_EXISTS",
  /**
   * Upload operations
   */
  UPLOAD_NOT_ALLOWED = "CONCESSION_CARD.UPLOAD.NOT_ALLOWED",
}
