export const enum EAdminErrorCodes {
  /**
   ** Payments operations
   */
  INCORRECT_PAYMENT_STATUS = "ADMIN.PAYMENTS.INCORRECT_STATUS",
  POST_PAYMENT_NOT_FOUND = "ADMIN.PAYMENTS.POST_PAYMENT_NOT_FOUND",
  POST_PAYMENT_WRONG_SYSTEM = "ADMIN.PAYMENTS.POST_PAYMENT_WRONG_SYSTEM",
  POST_PAYMENT_NO_PENDING_ITEMS = "ADMIN.PAYMENTS.POST_PAYMENT_NO_PENDING_ITEMS",
}
