export const enum EAwsSQSErrorCodes {
  /**
   * SQS operations
   */
  SQS_GET_QUEUE_ATTRIBUTES_FAILED = "AWS.SQS.GET_QUEUE_ATTRIBUTES_FAILED",
  SQS_RECEIVE_MESSAGES_FAILED = "AWS.SQS.RECEIVE_MESSAGES_FAILED",
  SQS_DELETE_MESSAGES_FAILED = "AWS.SQS.DELETE_MESSAGES_FAILED",
}
