import { EUserRoleName } from "src/modules/users/common/enums";

/**
 ** ROLE GROUPS
 */

export const INDIVIDUAL_ROLES = [
  EUserRoleName.IND_CLIENT,
  EUserRoleName.IND_LANGUAGE_BUDDY_INTERPRETER,
  EUserRoleName.IND_PROFESSIONAL_INTERPRETER,
] as const satisfies readonly EUserRoleName[];

export const IND_INTERPRETER_ROLES = [
  EUserRoleName.IND_PROFESSIONAL_INTERPRETER,
  EUserRoleName.IND_LANGUAGE_BUDDY_INTERPRETER,
] as const satisfies readonly EUserRoleName[];

export const CORPORATE_CLIENT_ROLES = [
  EUserRoleName.CORPORATE_CLIENTS_IND_USER,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_IND_USER,
] as const satisfies readonly EUserRoleName[];

export const CLIENT_ROLES = [
  EUserRoleName.IND_CLIENT,
  ...CORPORATE_CLIENT_ROLES,
] as const satisfies readonly EUserRoleName[];

export const INTERPRETER_ROLES = [
  ...IND_INTERPRETER_ROLES,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_IND_INTERPRETER,
] as const satisfies readonly EUserRoleName[];

export const INTERPRETER_AND_CLIENT_ROLES = [
  ...INTERPRETER_ROLES,
  ...CLIENT_ROLES,
] as const satisfies readonly EUserRoleName[];

export const ADMIN_ROLES = [
  EUserRoleName.SUPER_ADMIN,
  EUserRoleName.LFH_BOOKING_OFFICER,
  EUserRoleName.CORPORATE_CLIENTS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_CLIENTS_ADMIN,
  EUserRoleName.CORPORATE_CLIENTS_RECEPTIONIST,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_RECEPTIONIST,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_RECEPTIONIST,
] as const satisfies readonly EUserRoleName[];

/**
 ** COMPANY ADMIN ROLES
 */
export const LFH_ADMIN_ROLES = [
  EUserRoleName.SUPER_ADMIN,
  EUserRoleName.LFH_BOOKING_OFFICER,
] as const satisfies readonly EUserRoleName[];

export const CORPORATE_SUPER_ADMIN_ROLES = [
  EUserRoleName.CORPORATE_CLIENTS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_SUPER_ADMIN,
] as const satisfies readonly EUserRoleName[];

export const CORPORATE_ADMIN_ROLES = [
  EUserRoleName.CORPORATE_CLIENTS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_ADMIN,
] as const satisfies readonly EUserRoleName[];

export const CORPORATE_CLIENTS_COMPANY_ADMIN_ROLES = [
  EUserRoleName.CORPORATE_CLIENTS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_CLIENTS_ADMIN,
  EUserRoleName.CORPORATE_CLIENTS_RECEPTIONIST,
] as const satisfies readonly EUserRoleName[];

export const CORPORATE_INTERPRETING_PROVIDERS_COMPANY_ADMIN_ROLES = [
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_RECEPTIONIST,
] as const satisfies readonly EUserRoleName[];

export const CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_COMPANY_ADMIN_ROLES = [
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_RECEPTIONIST,
] as const satisfies readonly EUserRoleName[];

/**
 ** COMBINED ROLES
 */

export const COMPANY_ADMIN_ROLES = [
  ...CORPORATE_CLIENTS_COMPANY_ADMIN_ROLES,
  ...CORPORATE_INTERPRETING_PROVIDERS_COMPANY_ADMIN_ROLES,
  ...CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_COMPANY_ADMIN_ROLES,
] as const satisfies readonly EUserRoleName[];

/*
 * ALLOWED COMPANY EMPLOYEE ROLES
 */

export const ALLOWED_CORPORATE_CLIENTS_EMPLOYEE_ROLES = [
  EUserRoleName.CORPORATE_CLIENTS_ADMIN,
  EUserRoleName.CORPORATE_CLIENTS_RECEPTIONIST,
  EUserRoleName.CORPORATE_CLIENTS_IND_USER,
] as const satisfies readonly EUserRoleName[];

export const ALLOWED_CORPORATE_INTERPRETING_PROVIDERS_EMPLOYEE_ROLES = [
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_RECEPTIONIST,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_IND_INTERPRETER,
] as const satisfies readonly EUserRoleName[];

export const ALLOWED_CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_EMPLOYEE_ROLES = [
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_RECEPTIONIST,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_IND_USER,
] as const satisfies readonly EUserRoleName[];

export const ALLOWED_EMPLOYEE_ROLES = [
  ...ALLOWED_CORPORATE_CLIENTS_EMPLOYEE_ROLES,
  ...ALLOWED_CORPORATE_INTERPRETING_PROVIDERS_EMPLOYEE_ROLES,
  ...ALLOWED_CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_EMPLOYEE_ROLES,
] as const satisfies readonly EUserRoleName[];

/*
 * ROLES FOR RATE SELECT
 */
export const RATE_SELECT_ROLES_FOR_TAKER_FIELDS = [
  ...COMPANY_ADMIN_ROLES,
  ...CLIENT_ROLES,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_IND_INTERPRETER,
  EUserRoleName.INVITED_GUEST,
] as const satisfies readonly EUserRoleName[];

export const RATE_SELECT_ROLES_FOR_INTERPRETER_FIELDS = [
  EUserRoleName.IND_PROFESSIONAL_INTERPRETER,
  EUserRoleName.IND_LANGUAGE_BUDDY_INTERPRETER,
] as const satisfies readonly EUserRoleName[];

/*
 * ROLES FOR STATISTICS
 */

export const ADMIN_STATISTICS_ALLOWED_ROLES = [
  EUserRoleName.IND_PROFESSIONAL_INTERPRETER,
  EUserRoleName.IND_LANGUAGE_BUDDY_INTERPRETER,
  EUserRoleName.IND_CLIENT,
  EUserRoleName.CORPORATE_CLIENTS_IND_USER,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_IND_INTERPRETER,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_IND_USER,
] as const satisfies readonly EUserRoleName[];

export const ADMIN_STATISTICS_ALLOWED_INTERPRETERS_ROLES = [
  EUserRoleName.IND_PROFESSIONAL_INTERPRETER,
  EUserRoleName.IND_LANGUAGE_BUDDY_INTERPRETER,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_IND_INTERPRETER,
] as const satisfies readonly EUserRoleName[];

export const ROLES_WHICH_CAN_CANCEL_APPOINTMENT = [
  EUserRoleName.SUPER_ADMIN,
  EUserRoleName.LFH_BOOKING_OFFICER,
  EUserRoleName.IND_CLIENT,
  EUserRoleName.CORPORATE_CLIENTS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_CLIENTS_ADMIN,
  EUserRoleName.CORPORATE_CLIENTS_RECEPTIONIST,
  EUserRoleName.CORPORATE_CLIENTS_IND_USER,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_RECEPTIONIST,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_RECEPTIONIST,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_IND_USER,
] as const satisfies readonly EUserRoleName[];

/*
 * ROLES FOR TERMS UPLOAD EXEMPTION
 */
export const TERMS_UPLOAD_EXEMPTION_ROLES = [
  EUserRoleName.SUPER_ADMIN,
  EUserRoleName.INVITED_GUEST,
] as const satisfies readonly EUserRoleName[];
