export const enum ECompaniesErrorCodes {
  /**
   * Common operations
   */
  COMPANIES_COMMON_COMPANY_NOT_FOUND = "COMPANIES.COMMON.COMPANY_NOT_FOUND",
  COMPANIES_COMMON_NO_SUPER_ADMIN = "COMPANIES.COMMON.NO_SUPER_ADMIN",
  /**
   * Employee operations
   */
  EMPLOYEE_COMPANY_NOT_ACTIVATED = "COMPANIES.EMPLOYEE.COMPANY_NOT_ACTIVATED",
  EMPLOYEE_ROLE_NOT_ALLOWED = "COMPANIES.EMPLOYEE.ROLE_NOT_ALLOWED",
  /**
   * Query operations
   */
  QUERY_MAIN_COMPANY_NOT_FOUND = "COMPANIES.QUERY.MAIN_COMPANY_NOT_FOUND",
  /**
   * Companies operations
   */
  COMPANIES_ACTIVITY_SPHERE_REQUIRED = "COMPANIES.COMPANY.ACTIVITY_SPHERE_REQUIRED",
  COMPANIES_RESERVED_COMPANY_NAME = "COMPANIES.COMPANY.RESERVED_COMPANY_NAME",
  COMPANIES_PHONE_NUMBER_EXISTS = "COMPANIES.COMPANY.PHONE_NUMBER_EXISTS",
  COMPANIES_ADMIN_EMAIL_EXISTS = "COMPANIES.COMPANY.ADMIN_EMAIL_EXISTS",
  COMPANIES_INCORRECT_COMPANY_TYPE = "COMPANIES.COMPANY.INCORRECT_COMPANY_TYPE",
  COMPANIES_PHONE_OR_EMAIL_EXISTS = "COMPANIES.COMPANY.PHONE_OR_EMAIL_EXISTS",
  COMPANIES_OPERATED_BY_COMPANY_ID_REQUIRED = "COMPANIES.COMPANY.OPERATED_BY_COMPANY_ID_REQUIRED",
  COMPANIES_CORPORATE_CLIENT_EMAIL_EXISTS = "COMPANIES.COMPANY.CORPORATE_CLIENT_EMAIL_EXISTS",
  COMPANIES_REQUEST_ALREADY_ACCEPTED = "COMPANIES.COMPANY.REQUEST_ALREADY_ACCEPTED",
  COMPANIES_SET_ADMIN_INFO_FIRST = "COMPANIES.COMPANY.SET_ADMIN_INFO_FIRST",
  COMPANIES_COMPANY_ALREADY_REGISTERED = "COMPANIES.COMPANY.COMPANY_ALREADY_REGISTERED",
  COMPANIES_INVITATION_LINK_TIME_LIMIT = "COMPANIES.COMPANY.INVITATION_LINK_TIME_LIMIT",
  COMPANIES_COMMISSION_RATE_RESTRICTION = "COMPANIES.COMPANY.COMMISSION_RATE_RESTRICTION",
  COMPANIES_TIMEZONE_REQUIRED = "COMPANIES.COMPANY.TIMEZONE_REQUIRED",
  COMPANIES_FUNDING_SOURCE_IMMUTABLE_AFTER_ACTIVATION = "COMPANIES.COMPANY.FUNDING_SOURCE_IMMUTABLE_AFTER_ACTIVATION",
}
