import { EUserRoleName } from "src/modules/users/common/enums";

export const GET_APPOINTMENTS_FOR_CLIENT_ROLES: readonly EUserRoleName[] = [
  EUserRoleName.IND_CLIENT,
  EUserRoleName.CORPORATE_CLIENTS_IND_USER,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_IND_USER,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_RECEPTIONIST,
];

export const GET_APPOINTMENTS_FOR_INTERPRETER_ROLES: readonly EUserRoleName[] = [
  EUserRoleName.IND_PROFESSIONAL_INTERPRETER,
  EUserRoleName.IND_LANGUAGE_BUDDY_INTERPRETER,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_IND_INTERPRETER,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_RECEPTIONIST,
];

export const GET_APPOINTMENTS_FOR_ADMIN_ROLES: readonly EUserRoleName[] = [
  EUserRoleName.SUPER_ADMIN,
  EUserRoleName.LFH_BOOKING_OFFICER,
  EUserRoleName.CORPORATE_CLIENTS_SUPER_ADMIN,
  EUserRoleName.CORPORATE_CLIENTS_ADMIN,
  EUserRoleName.CORPORATE_CLIENTS_RECEPTIONIST,
];
