export const enum EBackyCheckErrorCodes {
  /**
   * Backy check SDK operations
   */
  SDK_HTTP_ERROR = "BACKY_CHECK.SDK.HTTP_ERROR",
  SDK_AUTH_ERROR = "BACKY_CHECK.SDK.AUTH_ERROR",
  /**
   * Service operations
   */
  SERVICE_FILE_UPLOAD_NOT_ALLOWED = "BACKY_CHECK.SERVICE.FILE_UPLOAD_NOT_ALLOWED",
  SERVICE_DOCUMENT_NOT_UPLOADED = "BACKY_CHECK.SERVICE.DOCUMENT_NOT_UPLOADED",
  SERVICE_WWCC_ALREADY_ENDED = "BACKY_CHECK.SERVICE.WWCC_ALREADY_ENDED",
  SERVICE_UPDATE_NOT_POSSIBLE = "BACKY_CHECK.SERVICE.UPDATE_NOT_POSSIBLE",
  SERVICE_ORDER_EXPIRED = "BACKY_CHECK.SERVICE.ORDER_EXPIRED",
  SERVICE_UPDATE_PENDING_REQUEST = "BACKY_CHECK.SERVICE.UPDATE_PENDING_REQUEST",
  SERVICE_NO_UPLOADED_FILE = "BACKY_CHECK.SERVICE.NO_UPLOADED_FILE",
  SERVICE_REQUEST_PENDING = "BACKY_CHECK.SERVICE.REQUEST_PENDING",
}
