export const enum EIeltsErrorCodes {
  /**
   * Verification operations
   */
  VERIFICATION_NATIVE_LANGUAGE_NOT_SET = "IELTS.VERIFICATION.NATIVE_LANGUAGE_NOT_SET",
  VERIFICATION_INCORRECT_CERTIFICATE_NUMBER = "IELTS.VERIFICATION.INCORRECT_CERTIFICATE_NUMBER",
  VERIFICATION_NAME_MISMATCH = "IELTS.VERIFICATION.NAME_MISMATCH",
  VERIFICATION_INSUFFICIENT_SCORE = "IELTS.VERIFICATION.INSUFFICIENT_SCORE",
  VERIFICATION_INVALID_USER_STATUS = "IELTS.VERIFICATION.INVALID_USER_STATUS",
  VERIFICATION_OTHER_LANGUAGE_CHECK_EXISTS = "IELTS.VERIFICATION.OTHER_LANGUAGE_CHECK_EXISTS",
  VERIFICATION_EXISTS_FOR_USER = "IELTS.VERIFICATION.EXISTS_FOR_USER",
  VERIFICATION_EXISTS_FOR_CERTIFICATE = "IELTS.VERIFICATION.EXISTS_FOR_CERTIFICATE",
  /**
   * SDK operations
   */
  SDK_HTTP_ERROR = "IELTS.SDK.HTTP_ERROR",
  SDK_AUTH_ERROR = "IELTS.SDK.AUTH_ERROR",
}
