export const enum EUsersErrorCodes {
  /*
   * Profile update policy operations
   */
  NAME_CHANGE_RESTRICTED_VERIFIED_DOCUMENTS = "USERS.PROFILE_UPDATE_POLICY.NAME_CHANGE_RESTRICTED_VERIFIED_DOCUMENTS",
  TIMEZONE_REQUIRED = "USERS.PROFILE_UPDATE_POLICY.TIMEZONE_REQUIRED",
  NAME_CHANGE_RESTRICTED_PROFESSIONAL_DOCUMENTS = "USERS.PROFILE_UPDATE_POLICY.NAME_CHANGE_RESTRICTED_PROFESSIONAL_DOCUMENTS",
  EMAIL_CHANGE_RESTRICTED_BACKGROUND_CHECK = "USERS.PROFILE_UPDATE_POLICY.EMAIL_CHANGE_RESTRICTED_BACKGROUND_CHECK",
  /*
   * Profiles operations
   */
  PROFILE_ALREADY_EXISTS = "USERS.PROFILES.PROFILE_ALREADY_EXISTS",
  /*
   * Password operations
   */
  PASSWORD_NOT_FOUND_TRY_THIRD_PARTY = "USERS.PASSWORD.PASSWORD_NOT_FOUND_TRY_THIRD_PARTY",
  USER_NO_PHONE_NUMBER = "USERS.PASSWORD.USER_NO_PHONE_NUMBER",

  /*
   * Registration steps operations
   */
  EMAIL_ALREADY_REGISTERED = "USERS.REGISTRATION_STEPS.EMAIL_ALREADY_REGISTERED",
  CODE_INCORRECT = "USERS.REGISTRATION_STEPS.CODE_INCORRECT",
  UNABLE_ADD_PASSWORD = "USERS.REGISTRATION_STEPS.UNABLE_ADD_PASSWORD",
  PHONE_NUMBER_ALREADY_EXISTS = "USERS.REGISTRATION_STEPS.PHONE_NUMBER_ALREADY_EXISTS",
  PHONE_VERIFICATION_FAILED = "USERS.REGISTRATION_STEPS.PHONE_VERIFICATION_FAILED",
  ALREADY_AGREED_TO_TERMS = "USERS.REGISTRATION_STEPS.ALREADY_AGREED_TO_TERMS",
  /*
   * Registration operations
   */
  USER_ALREADY_REGISTERED_WITH_ROLE = "USERS.REGISTRATION.USER_ALREADY_REGISTERED_WITH_ROLE",
  PHONE_NUMBER_MISMATCH = "USERS.REGISTRATION.PHONE_NUMBER_MISMATCH",
  /*
   * Users operations
   */
  EMAIL_ALREADY_REGISTERED_CHANGE = "USERS.USER.EMAIL_ALREADY_REGISTERED",
  PHONE_NUMBER_ALREADY_EXISTS_CHANGE = "USERS.USER.PHONE_NUMBER_ALREADY_EXISTS",
  PASSWORD_NOT_SET = "USERS.USER.PASSWORD_NOT_SET",
  INCORRECT_CURRENT_PASSWORD = "USERS.USER.INCORRECT_CURRENT_PASSWORD",
  NEW_PASSWORD_SAME_AS_CURRENT = "USERS.USER.NEW_PASSWORD_SAME_AS_CURRENT",
  COMPANY_DELETED = "USERS.USER.COMPANY_DELETED",
  OPERATED_COMPANY_NOT_FOUND = "USERS.USER.OPERATED_COMPANY_NOT_FOUND",
  COMPANY_DEACTIVATED = "USERS.USER.COMPANY_DEACTIVATED",
  COMPANY_DELETED_CONTACT_ADMIN = "USERS.USER.COMPANY_DELETED_CONTACT_ADMIN",
  ACCOUNT_DELETED_USE_RESTORATION = "USERS.USER.ACCOUNT_DELETED_USE_RESTORATION",
  ACCOUNT_LOCKED = "USERS.USER.ACCOUNT_LOCKED",
}
