export const enum ETokensErrorCodes {
  /*
   * Apple operations
   */
  TOKEN_DECODE_FAILED = "TOKENS.APPLE.TOKEN_DECODE_FAILED",
  TOKEN_EXPIRED = "TOKENS.APPLE.TOKEN_EXPIRED",
  PUBLIC_KEY_RETRIEVAL_FAILED = "TOKENS.APPLE.PUBLIC_KEY_RETRIEVAL_FAILED",
  KEY_SIGNATURES_MISMATCH = "TOKENS.APPLE.KEY_SIGNATURES_MISMATCH",
  TOKEN_VERIFICATION_FAILED = "TOKENS.APPLE.TOKEN_VERIFICATION_FAILED",
}
