export const enum EAwsChimeSdkErrorCodes {
  /**
   * Chime SDK operations
   */
  CHIME_SDK_CREATE_MEETING_FAILED = "AWS.CHIME_SDK.CREATE_MEETING_FAILED",
  CHIME_SDK_GET_MEETING_FAILED = "AWS.CHIME_SDK.GET_MEETING_FAILED",
  CHIME_SDK_DELETE_MEETING_FAILED = "AWS.CHIME_SDK.DELETE_MEETING_FAILED",
  CHIME_SDK_LIST_ATTENDEES_FAILED = "AWS.CHIME_SDK.LIST_ATTENDEES_FAILED",
  CHIME_SDK_GET_ATTENDEE_FAILED = "AWS.CHIME_SDK.GET_ATTENDEE_FAILED",
  CHIME_SDK_CREATE_ATTENDEE_FAILED = "AWS.CHIME_SDK.CREATE_ATTENDEE_FAILED",
  CHIME_SDK_UPDATE_ATTENDEE_FAILED = "AWS.CHIME_SDK.UPDATE_ATTENDEE_FAILED",
  CHIME_SDK_UPDATE_ATTENDEES_FAILED = "AWS.CHIME_SDK.UPDATE_ATTENDEES_FAILED",
  CHIME_SDK_DELETE_ATTENDEE_FAILED = "AWS.CHIME_SDK.DELETE_ATTENDEE_FAILED",
  CHIME_SDK_START_CAPTURE_PIPELINE_FAILED = "AWS.CHIME_SDK.START_CAPTURE_PIPELINE_FAILED",
  CHIME_SDK_CREATE_CONCATENATION_PIPELINE_FAILED = "AWS.CHIME_SDK.CREATE_CONCATENATION_PIPELINE_FAILED",
  CHIME_SDK_CREATE_SIP_CALL_FAILED = "AWS.CHIME_SDK.CREATE_SIP_CALL_FAILED",
}
