import {
  NUMBER_OF_MINUTES_IN_DAY,
  NUMBER_OF_MINUTES_IN_FOUR_DAYS,
  NUMBER_OF_MINUTES_IN_HALF_HOUR,
  NUMBER_OF_MINUTES_IN_THREE_DAYS,
  NUMBER_OF_MINUTES_IN_TWELVE_HOURS,
  NUMBER_OF_MINUTES_IN_TWO_DAYS,
} from "src/common/constants";
import { OldEPaymentStatus } from "src/modules/payments/common/enums";

export const OLD_MIN_NUM_DAYS_BEFORE_APPOINTMENT_TO_PAY = 4;
export const OLD_MINUTES_BEFORE_START_AS_REASON_TO_CANCEL = 5;
export const OLD_PAYMENT_FRAMES: readonly number[] = [
  NUMBER_OF_MINUTES_IN_HALF_HOUR,
  NUMBER_OF_MINUTES_IN_TWELVE_HOURS,
  NUMBER_OF_MINUTES_IN_DAY,
  NUMBER_OF_MINUTES_IN_TWO_DAYS,
  NUMBER_OF_MINUTES_IN_THREE_DAYS,
  NUMBER_OF_MINUTES_IN_FOUR_DAYS,
];

export const OLD_UNFINISHED_DEPOSIT_CHARGE_STATUSES: readonly OldEPaymentStatus[] = [
  OldEPaymentStatus.DEPOSIT_PAYMENT_REQUEST_INITIALIZING,
  OldEPaymentStatus.DEPOSIT_PAYMENT_REQUEST_CREATING,
  OldEPaymentStatus.BANK_ACCOUNT_CHARGE_PENDING,
  OldEPaymentStatus.PAYMENT_REQUEST_CREATED,
  OldEPaymentStatus.BANK_ACCOUNT_CHARGE_TRANSACTION_CREATED,
  OldEPaymentStatus.BANK_ACCOUNT_CHARGE_SUCCEEDED,
];
