export const enum EPaymentInformationErrorCodes {
  /**
   * Common operations
   */
  COMMON_USER_PAYMENT_INFO_NOT_FILLED = "PAYMENT_INFORMATION.COMMON.PAYMENT_INFO_NOT_FILLED",
  COMMON_STRIPE_ACCOUNT_NOT_EXIST = "PAYMENT_INFORMATION.COMMON.STRIPE_ACCOUNT_NOT_EXIST",
  COMMON_PAYPAL_PAYER_ID_MISSING = "PAYMENT_INFORMATION.COMMON.PAYPAL_PAYER_ID_MISSING",
  COMMON_COMPANY_NOT_FOUND = "PAYMENT_INFORMATION.COMMON.COMPANY_NOT_FOUND",
  /**
   * General operations
   */
  GENERAL_INCORRECT_ROLE = "PAYMENT_INFORMATION.GENERAL.INCORRECT_ROLE",
  GENERAL_BOTH_SYSTEMS_REQUIRED = "PAYMENT_INFORMATION.GENERAL.BOTH_SYSTEMS_REQUIRED",
  GENERAL_CANNOT_DELETE_WITH_APPOINTMENTS = "PAYMENT_INFORMATION.GENERAL.CANNOT_DELETE_WITH_APPOINTMENTS",
  /**
   * Individual payment operations
   */
  INDIVIDUAL_PROFILE_NOT_FILLED = "PAYMENT_INFORMATION.INDIVIDUAL.PROFILE_NOT_FILLED",
  INDIVIDUAL_CONTACT_EMAIL_NOT_FILLED = "PAYMENT_INFORMATION.INDIVIDUAL.CONTACT_EMAIL_NOT_FILLED",
  INDIVIDUAL_ALREADY_ONBOARDED = "PAYMENT_INFORMATION.INDIVIDUAL.ALREADY_ONBOARDED",
  /**
   * Corporate payment operations
   */
  CORPORATE_PAYMENT_INFO_NOT_FILLED = "PAYMENT_INFORMATION.CORPORATE.PAYMENT_INFO_NOT_FILLED",
  CORPORATE_ALREADY_ONBOARDED = "PAYMENT_INFORMATION.CORPORATE.ALREADY_ONBOARDED",
  CORPORATE_CONTACT_EMAIL_NOT_FILLED = "PAYMENT_INFORMATION.CORPORATE.CONTACT_EMAIL_NOT_FILLED",
}
