export const enum EAwsMessagingSdkErrorCodes {
  /**
   * Messaging SDK operations
   */
  MESSAGING_SDK_CREATE_APP_INSTANCE_FAILED = "AWS.MESSAGING_SDK.CREATE_APP_INSTANCE_FAILED",
  MESSAGING_SDK_CREATE_APP_INSTANCE_USER_FAILED = "AWS.MESSAGING_SDK.CREATE_APP_INSTANCE_USER_FAILED",
  MESSAGING_SDK_CREATE_APP_INSTANCE_ADMIN_FAILED = "AWS.MESSAGING_SDK.CREATE_APP_INSTANCE_ADMIN_FAILED",
  MESSAGING_SDK_LIST_CHANNEL_MESSAGES_FAILED = "AWS.MESSAGING_SDK.LIST_CHANNEL_MESSAGES_FAILED",
  MESSAGING_SDK_DELETE_CHANNEL_MESSAGE_FAILED = "AWS.MESSAGING_SDK.DELETE_CHANNEL_MESSAGE_FAILED",
  MESSAGING_SDK_CREATE_CHANNEL_FAILED = "AWS.MESSAGING_SDK.CREATE_CHANNEL_FAILED",
  MESSAGING_SDK_ADD_MEMBER_TO_CHANNEL_FAILED = "AWS.MESSAGING_SDK.ADD_MEMBER_TO_CHANNEL_FAILED",
  MESSAGING_SDK_DELETE_CHANNEL_FAILED = "AWS.MESSAGING_SDK.DELETE_CHANNEL_FAILED",
}
