export const enum EAppointmentSharedErrorCodes {
  /**
   ** Creation validation
   */
  TIME_ALREADY_RESERVED = "APPOINTMENT_SHARED.CREATION_VALIDATION.TIME_ALREADY_RESERVED",
  /**
   ** Update validation
   */
  UPDATES_NOT_ALLOWED_WITHIN_TIME_LIMIT = "APPOINTMENT_SHARED.UPDATE_VALIDATION.UPDATES_NOT_ALLOWED_WITHIN_TIME_LIMIT",
  /**
   ** Cancellation validation
   */
  INCORRECT_FIELD = "APPOINTMENT_SHARED.CANCELLATION_VALIDATION.INCORRECT_FIELD",
  CANNOT_BE_CANCELLED = "APPOINTMENT_SHARED.CANCELLATION_VALIDATION.CANNOT_BE_CANCELLED",
  /**
   ** Check in/out validation
   */
  INVALID_COMMUNICATION_TYPE = "APPOINTMENT_SHARED.CHECK_IN_OUT_VALIDATION.INVALID_COMMUNICATION_TYPE",
  MUST_BE_LIVE_STATUS = "APPOINTMENT_SHARED.CHECK_IN_OUT_VALIDATION.MUST_BE_LIVE_STATUS",
  ALTERNATIVE_END_TIME_ERROR = "APPOINTMENT_SHARED.CHECK_IN_OUT_VALIDATION.ALTERNATIVE_END_TIME_ERROR",
  ADMINS_CANNOT_CHECK_IN = "APPOINTMENT_SHARED.CHECK_IN_OUT_VALIDATION.ADMINS_CANNOT_CHECK_IN",
  CLIENTS_CANNOT_CHECK_IN_FACE_TO_FACE = "APPOINTMENT_SHARED.CHECK_IN_OUT_VALIDATION.CLIENTS_CANNOT_CHECK_IN_FACE_TO_FACE",
  CLIENTS_CANNOT_CHECK_IN_ALTERNATIVE = "APPOINTMENT_SHARED.CHECK_IN_OUT_VALIDATION.CLIENTS_CANNOT_CHECK_IN_ALTERNATIVE",
  CLIENTS_CANNOT_CHECK_OUT_FACE_TO_FACE = "APPOINTMENT_SHARED.CHECK_IN_OUT_VALIDATION.CLIENTS_CANNOT_CHECK_OUT_FACE_TO_FACE",
  INTERPRETERS_CANNOT_CHECK_OUT_ALTERNATIVE = "APPOINTMENT_SHARED.CHECK_IN_OUT_VALIDATION.INTERPRETERS_CANNOT_CHECK_OUT_ALTERNATIVE",
}
