export const enum EFileManagementErrorCodes {
  /**
   * Upload operations
   */
  UPLOAD_FILE_SIZE_EXCEEDED = "FILE_MANAGEMENT.UPLOAD.FILE_SIZE_EXCEEDED",
  UPLOAD_INCORRECT_CONTENT_TYPE = "FILE_MANAGEMENT.UPLOAD.INCORRECT_CONTENT_TYPE",
  /**
   * Validation operations
   */
  VALIDATION_ROLE_NOT_ALLOWED = "FILE_MANAGEMENT.VALIDATION.ROLE_NOT_ALLOWED",
  VALIDATION_ROLE_NOT_SPECIFIED = "FILE_MANAGEMENT.VALIDATION.ROLE_NOT_SPECIFIED",
  VALIDATION_ROLE_AND_DOCUMENT_TYPE_REQUIRED = "FILE_MANAGEMENT.VALIDATION.ROLE_AND_DOCUMENT_TYPE_REQUIRED",
  VALIDATION_UNKNOWN_FILE_TYPE = "FILE_MANAGEMENT.VALIDATION.UNKNOWN_FILE_TYPE",
}
