/* eslint-disable @typescript-eslint/no-duplicate-enum-values */
export const enum EFileUploadSizeLimitMB {
  AWS_S3_UI_LANGUAGES_LIMIT = 1,
  AWS_S3_CONTRACT_LIMIT = 10,
  AWS_S3_BACKYCHECK_DOCS_LIMIT = 10,
  AWS_S3_CONCESSION_CARD_LIMIT = 10,
  AWS_S3_LANGUAGE_DOCS_LIMIT = 10,
  AWS_S3_RIGHT_TO_WORK_CHECK_DOCS_LIMIT = 10,
  AWS_S3_TERMS_LIMIT = 10,
  AWS_S3_CONTENT_MANAGEMENT_LIMIT = 10,
  AWS_S3_COMPANY_DOCUMENT_LIMIT = 10,
  AWS_S3_USER_AVATARS_LIMIT = 5,
  AWS_S3_CHANNELS_LIMIT = 5,
  AWS_S3_PROMO_CAMPAIGNS_LIMIT = 5,
}
