export const enum EPromoCampaignsErrorCodes {
  /*
   * Common operations
   */
  BANNER_NOT_FOUND = "PROMO_CAMPAIGNS.COMMON.NOT_FOUND",
  /*
   * Validation operations
   */
  CAMPAIGN_NOT_UPDATABLE = "PROMO_CAMPAIGNS.VALIDATION.NOT_UPDATABLE",
  CORPORATE_PROVIDER_NOT_ALLOWED = "PROMO_CAMPAIGNS.VALIDATION.CORPORATE_PROVIDER_NOT_ALLOWED",
  COMPANY_ALREADY_ASSIGNED = "PROMO_CAMPAIGNS.VALIDATION.COMPANY_ALREADY_ASSIGNED",
  CORPORATE_FIELDS_NOT_UPDATABLE = "PROMO_CAMPAIGNS.VALIDATION.CORPORATE_FIELDS_NOT_UPDATABLE",
  RESTRICTED_STATUS_FIELDS = "PROMO_CAMPAIGNS.VALIDATION.RESTRICTED_STATUS_FIELDS",
  STATUS_CHANGE_BEFORE_START = "PROMO_CAMPAIGNS.VALIDATION.STATUS_CHANGE_BEFORE_START",
  NAME_OR_CODE_EXISTS = "PROMO_CAMPAIGNS.VALIDATION.NAME_OR_CODE_EXISTS",
  ALL_NEW_PERSONAL_CONFLICT = "PROMO_CAMPAIGNS.VALIDATION.ALL_NEW_PERSONAL_CONFLICT",
  START_DATE_AFTER_END_DATE = "PROMO_CAMPAIGNS.VALIDATION.START_DATE_AFTER_END_DATE",
  INVALID_PROMO_CODE = "PROMO_CAMPAIGNS.VALIDATION.INVALID_PROMO_CODE",
  PERSONAL_ALREADY_ASSIGNED = "PROMO_CAMPAIGNS.VALIDATION.PERSONAL_ALREADY_ASSIGNED",
  CONDITIONS_URL_TARGET_INVALID = "PROMO_CAMPAIGNS.VALIDATION.CONDITIONS_URL_TARGET_INVALID",
  BANNER_DISPLAY_WITHOUT_BANNER = "PROMO_CAMPAIGNS.VALIDATION.BANNER_DISPLAY_WITHOUT_BANNER",
  BANNER_DISPLAY_TARGET_INVALID = "PROMO_CAMPAIGNS.VALIDATION.BANNER_DISPLAY_TARGET_INVALID",
}
