export const enum EPaymentsErrorCodes {
  /**
   * Authorization service operations
   */
  AUTHORIZE_PAYMENT_FAILED = "PAYMENTS.AUTHORIZATION.AUTHORIZE_PAYMENT_FAILED",
  /**
   * Authorization cancel service operations
   */
  CANCEL_AUTHORIZATION_FAILED = "PAYMENTS.AUTHORIZATION_CANCEL.CANCEL_AUTHORIZATION_FAILED",
  HANDLE_LATE_CANCELLATION_FAILED = "PAYMENTS.AUTHORIZATION_CANCEL.HANDLE_LATE_CANCELLATION_FAILED",
  /**
   * Capture service operations
   */
  CAPTURE_PAYMENT_FAILED = "PAYMENTS.CAPTURE.CAPTURE_PAYMENT_FAILED",
  /**
   * Corporate deposit service operations
   */
  CHARGE_FROM_DEPOSIT_FAILED = "PAYMENTS.CORPORATE_DEPOSIT.CHARGE_FROM_DEPOSIT_FAILED",
  /**
   * Corporate post payment service operations
   */
  POST_PAYMENT_FAILED = "PAYMENTS.CORPORATE_POST_PAYMENT.POST_PAYMENT_FAILED",
  /**
   * Corporate commission service operations
   */
  PROCESS_SAME_COMPANY_COMMISSION_FAILED = "PAYMENTS.CORPORATE_COMMISSION.PROCESS_SAME_COMPANY_COMMISSION_FAILED",
  /**
   * Transfer service operations
   */
  TRANSFER_AND_PAYOUT_FAILED = "PAYMENTS.TRANSFER.TRANSFER_AND_PAYOUT_FAILED",
  MAKE_PAYOUT_RECORD_FAILED = "PAYMENTS.TRANSFER.MAKE_PAYOUT_RECORD_FAILED",
  /**
   * Wait list service operations
   */
  REDIRECT_TO_WAIT_LIST_FAILED = "PAYMENTS.WAIT_LIST.REDIRECT_TO_WAIT_LIST_FAILED",
  /**
   * Validation service operations
   */
  VALIDATION_FAILURE_PROCESSING_FAILED = "PAYMENTS.VALIDATION.VALIDATION_FAILURE_PROCESSING_FAILED",
  /**
   * Query service operations
   */
  RECEIPT_NOT_EXIST = "PAYMENTS.QUERY.RECEIPT_NOT_EXIST",
}
