export const enum EAccountActivationErrorCodes {
  /**
   ** User operations
   */
  USER_NOT_FOUND = "ACCOUNT_ACTIVATION.USER.NOT_FOUND",
  USER_ROLE_NOT_ACTIVE = "ACCOUNT_ACTIVATION.USER.ROLE_NOT_ACTIVE",
  /**
   ** Account operations
   */
  ACCOUNT_ALREADY_ACTIVE = "ACCOUNT_ACTIVATION.ACCOUNT.ALREADY_ACTIVE",
  /**
   ** Session operations
   */
  LAST_SESSION_NOT_EXIST = "ACCOUNT_ACTIVATION.SESSION.LAST_SESSION_NOT_EXIST",
  CLIENT_INFO_REQUIRED = "ACCOUNT_ACTIVATION.SESSION.CLIENT_INFO_REQUIRED",
  PLATFORM_INFO_REQUIRED = "ACCOUNT_ACTIVATION.SESSION.PLATFORM_INFO_REQUIRED",

  /**
   ** Company operations
   */
  COMPANY_NOT_EXIST = "ACCOUNT_ACTIVATION.COMPANY.NOT_EXIST",
  COMPANY_STEPS_NOT_FOUND = "ACCOUNT_ACTIVATION.COMPANY.STEPS_NOT_FOUND",
  COMPANY_NO_SUPER_ADMIN = "ACCOUNT_ACTIVATION.COMPANY.NO_SUPER_ADMIN",
  COMPANY_ALREADY_ACTIVE = "ACCOUNT_ACTIVATION.COMPANY.ALREADY_ACTIVE",
  COMPANY_NOT_ACTIVE = "ACCOUNT_ACTIVATION.COMPANY.NOT_ACTIVE",
  /**
   ** Validation operations
   */
  REQUIRED_INFO_NOT_PROVIDED = "ACCOUNT_ACTIVATION.VALIDATION.REQUIRED_INFO_NOT_PROVIDED",
  /**
   ** Step names
   */
  STEP_PROFILE_INFORMATION = "ACCOUNT_ACTIVATION.STEP_NAMES.PROFILE_INFORMATION",
  STEP_QUESTIONNAIRE = "ACCOUNT_ACTIVATION.STEP_NAMES.QUESTIONNAIRE",
  STEP_IDENTITY_VERIFICATION = "ACCOUNT_ACTIVATION.STEP_NAMES.IDENTITY_VERIFICATION",
  STEP_ABN_VERIFICATION = "ACCOUNT_ACTIVATION.STEP_NAMES.ABN_VERIFICATION",
  STEP_DOCUSIGN_VERIFICATION = "ACCOUNT_ACTIVATION.STEP_NAMES.DOCUSIGN_VERIFICATION",
  STEP_BACKGROUND_CHECK = "ACCOUNT_ACTIVATION.STEP_NAMES.BACKGROUND_CHECK",
  STEP_NAATI_VERIFICATION = "ACCOUNT_ACTIVATION.STEP_NAMES.NAATI_VERIFICATION",
  STEP_RIGHT_TO_WORK_LANGUAGE_BUDDY = "ACCOUNT_ACTIVATION.STEP_NAMES.RIGHT_TO_WORK_LANGUAGE_BUDDY",
  STEP_INSURANCE_VERIFICATION = "ACCOUNT_ACTIVATION.STEP_NAMES.INSURANCE_VERIFICATION",
  STEP_CONCESSION_CARD = "ACCOUNT_ACTIVATION.STEP_NAMES.CONCESSION_CARD",
  STEP_RIGHT_TO_WORK_CHECK = "ACCOUNT_ACTIVATION.STEP_NAMES.RIGHT_TO_WORK_CHECK",
  STEP_PAYMENT_INFORMATION = "ACCOUNT_ACTIVATION.STEP_NAMES.PAYMENT_INFORMATION",
}
