export const enum EMembershipErrorCodes {
  /**
   * Payment operations
   */
  PAYMENTS_PAYMENT_INFO_MISSING = "MEMBERSHIPS.PAYMENTS.PAYMENT_INFO_MISSING",
  PAYMENTS_PAYMENT_INFO_NOT_FOUND = "MEMBERSHIPS.PAYMENTS.PAYMENT_INFO_NOT_FOUND",
  PAYMENTS_INVOICE_NOT_SUBSCRIPTION = "MEMBERSHIPS.PAYMENTS.INVOICE_NOT_SUBSCRIPTION",
  /**
   * Price operations
   */
  PRICE_NOT_FOUND_FOR_REGION = "MEMBERSHIPS.PRICE.NOT_FOUND_FOR_REGION",
  /**
   * Deactivation operations
   */
  DEACTIVATION_ALREADY_DEACTIVATED = "MEMBERSHIPS.DEACTIVATION.ALREADY_DEACTIVATED",
}
