export const enum EAppointmentOrderWorkflowErrorCodes {
  /**
   ** Creation operations
   */
  UNABLE_TO_CALCULATE_NEXT_REPEAT_TIME = "APPOINTMENT_ORDER_WORKFLOW.CREATION.UNABLE_TO_CALCULATE_NEXT_REPEAT_TIME",
  /**
   ** Recreation operations
   */
  APPOINTMENT_MISSING_GROUP_ID = "APPOINTMENT_ORDER_WORKFLOW.RECREATION.APPOINTMENT_MISSING_GROUP_ID",
  NO_CLIENT_IN_APPOINTMENT = "APPOINTMENT_ORDER_WORKFLOW.RECREATION.NO_CLIENT_IN_APPOINTMENT",
  NO_APPOINTMENTS_FOR_GROUP_RECREATION = "APPOINTMENT_ORDER_WORKFLOW.RECREATION.NO_APPOINTMENTS_FOR_GROUP_RECREATION",
  APPOINTMENT_MISSING_GROUP_ID_OR_CLIENT = "APPOINTMENT_ORDER_WORKFLOW.RECREATION.APPOINTMENT_MISSING_GROUP_ID_OR_CLIENT",
}
