export const enum ECommonErrorCodes {
  /**
   * Access operations
   */
  ACCESS_FORBIDDEN_REQUEST = "COMMON.ACCESS.FORBIDDEN_REQUEST",
  /**
   * Validation operations
   */
  FILE_NOT_RECEIVED = "COMMON.VALIDATION.FILE_NOT_RECEIVED",
  /**
   * Pipes operations
   */
  BODY_MUST_BE_NON_EMPTY_OBJECT = "COMMON.PIPES.BODY_MUST_BE_NON_EMPTY_OBJECT",
  VALUE_REQUIRED = "COMMON.PIPES.VALUE_REQUIRED",
  ONLY_ONE_ORDERING_FIELD_ALLOWED = "COMMON.PIPES.ONLY_ONE_ORDERING_FIELD_ALLOWED",
  /**
   * Filters operations
   */
  UNEXPECTED_ERROR = "COMMON.FILTERS.UNEXPECTED_ERROR",
  UNAUTHORIZED = "COMMON.FILTERS.UNAUTHORIZED",
  /**
   * Utils operations
   */
  ENTITY_NOT_FOUND = "COMMON.UTILS.ENTITY_NOT_FOUND",
  INVALID_DECIMAL_EMPTY_OR_NOT_STRING = "COMMON.UTILS.INVALID_DECIMAL_EMPTY_OR_NOT_STRING",
  INVALID_DECIMAL_NAN = "COMMON.UTILS.INVALID_DECIMAL_NAN",
  INVALID_DECIMAL_NAN_OR_INFINITE = "COMMON.UTILS.INVALID_DECIMAL_NAN_OR_INFINITE",
}
