export const enum EMultiWayParticipantErrorCodes {
  /**
   * Participant operations
   */
  PARTICIPANT_CLIENT_REQUIRED_FOR_ADD = "MULTI_WAY_PARTICIPANT.PARTICIPANT.CLIENT_REQUIRED_FOR_ADD",
  PARTICIPANT_CLIENT_REQUIRED_FOR_UPDATE = "MULTI_WAY_PARTICIPANT.PARTICIPANT.CLIENT_REQUIRED_FOR_UPDATE",
}
