export const enum ERemovalErrorCodes {
  /*
   * Request operations
   */
  EMAIL_NOT_FILLED = "REMOVAL.REQUEST.EMAIL_NOT_FILLED",
  COMPANY_NOT_FOUND = "REMOVAL.REQUEST.COMPANY_NOT_FOUND",
  ADMIN_DATA_NOT_FILLED = "REMOVAL.REQUEST.ADMIN_DATA_NOT_FILLED",
  /*
   * Shared operations
   */
  USER_HAS_UNCOMPLETED_APPOINTMENTS = "REMOVAL.SHARED.USER_HAS_UNCOMPLETED_APPOINTMENTS",
  COMPANY_HAS_UNCOMPLETED_APPOINTMENTS = "REMOVAL.SHARED.COMPANY_HAS_UNCOMPLETED_APPOINTMENTS",
  /*
   * Restoration operations
   */
  INCORRECT_RESTORATION_KEY = "REMOVAL.RESTORATION.INCORRECT_KEY",
  COMPANY_NOT_IN_DELETE_WAITING = "REMOVAL.RESTORATION.COMPANY_NOT_IN_DELETE_WAITING",
}
